### ISSUE TITLE
Resize handler on div

### ISSUE THREAD

**Issue by intellisense** [froala/wysiwyg-editor#1025]
Hi,

Cheers for building this awesome editor. I have one use case if you could help me. I am inserting a video into editor using insert html command like this:

```
<span class="fr-video fr-dvb" contenteditable="false">
  <div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" src="https://some.com/url" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
  </div>
</span>
```

When resize is enable on video the editor set width and height on iframe. I don't want to do that as I want the iframe to be responsive (using twitter bootstrap embed responsive classes) within its parent. I want to have width and height set to wrapper containing classes `fr-video fr-dvb` instead. In this way the iframe will automatically adjust using parent width and height.

OR (If that's not possible)

I can disable video resize but then I need to have resizer on parent block. So is there some class if we can add to a container and it enabels resizer/alignment on any block we want to and not just image or iframe/video/object?

P.S. Same goes for image as well. So the best solution is if there some generic class we add to enable resizer/alignment tools on any block we want to? (This will gives a lot of freedom and power)

Thanks!

**Comment by stefanneculai** [comment]
If you want to achieve that, then you'd have to modify the video plugin for that. Unfortunately, it is not possible to have a generic resizer because video DOM structure is different than image DOM structure and that would happen in the most cases. The best way to do that is to use the unminified JS (which comes with the Advanced/OEM license) and change it for your needs.
