### ISSUE TITLE
Sticky toolbar (stick to top when scrolling) not working in Firefox and Safari

### ISSUE THREAD

**Issue by intellisense** [froala/wysiwyg-editor#1042]
Just checked on `Firefox 44.0` and `Safari 8.0.4` (Apparently it never works on Firefox or Safari as I tried different version as well)

**Comment by stefanneculai** [comment]
Most probably one  one of the parents has the CSS property `overflow: hidden`. Because of how the Firefox and Safari positioning is designed, the toolbar won't stick correctly in such cases.

**Comment by viion** [comment]
Doesn't seem to work on Chrome Version 48.0.2564.116 either, trying this page: https://www.froala.com/wysiwyg-editor/docs/examples/sticky-toolbar - It didn't work putting the code on a page of its own either.

Scrolling does nothing, the toolbar stays where it is.

**Comment by stefanneculai** [comment]
@viion on the page you sent us the link the toolbar should stay at the top of the editor as it does.

**Comment by viion** [comment]
My impression of a "Sticky Toolbar" would be that when I scroll down, the toolbar is always visible even if the editor becomes off page. Redactor does this so that if you have very large documents, when you scroll the Toolbar sticks to the top at all times and is visible regardless of the height of the editor.

The page I linked does not do this, it just acts like the normal editor, here is a screenshot where the toolbar is not visible:

![](http://i.imgur.com/rDUCiL1.png)

**Comment by stefanneculai** [comment]
The toolbar is sticky at the top by default (`toolbarSticky: true`). If you disable the option, then the toolbar  will not stay sticky at the top, but scroll along with the content. That is explained on the page as well:

> In this example, when you scroll down, the rich text editor's toolbar will scroll along with the page and it will no longer be visible at the top of the page.

**Comment by viion** [comment]
Ah I see, I miss-understood as I was expecting a feature to be shown on the page about the feature, and not disabled... No worries, cheers!

**Comment by bindea-mihai** [comment]
Hi @stefanneculai,
I was wondering why does the sticky toolbar behaves different in chrome vs firefox, meaning that in chrome you have the 'fr-sticky-on' and 'ft-sticky-off' classes, which use position fixed and top 0, and in firefox you have the 'fr-sticky' class that uses position: sticky?
Since position sticky has the overflow bug in firefox, can't you use here the same approach as you do in chrome? 

Chrome:
![image](https://user-images.githubusercontent.com/10978867/39918022-eadff5ca-5517-11e8-930f-2e3be1bc1c9e.png)

Firefox:
![image](https://user-images.githubusercontent.com/10978867/39918038-f5d67198-5517-11e8-9699-da55d15816d4.png)
