### ISSUE TITLE
Get image in base64 or blob format

### ISSUE THREAD

**Issue by Qlipoth** [froala/wysiwyg-editor#1080]
Hello, I use froala.
1) How can I get a picture in base64 or blob format after insertion? 
2) How to prevent the uploading of an image after insertion? I do not want to send a request to the server after each insert image

**Comment by stefanneculai** [comment]
1) In the `image.beforeUpload` event you should convert image to base64 and insert it if you want so. However, we do not recommend this because browser performance might drop a lot when using base64 images.
2) The same event can be used for that.

We use this repo for bug tracking, not for support, therefore if you have questions or need help integrating the editor please [contact us](https://www.froala.com/wysiwyg-editor/contact) instead of opening an issue.

**Comment by cybervanes** [comment]
Has anybody figured this one out? Can anybody share an example?

**Comment by AlverthoMartinez** [comment]
https://wysiwyg-editor.froala.help/hc/en-us/articles/115000555949-Can-I-insert-images-as-base64-

**Comment by cybervanes** [comment]
Nice solution, thanks very much.

I only needed this for an offline iOS application. Once synced back to online database, images are converted back to raw files and base64 text removed.

Thanks Again


On Jul 11, 2017, at 2:37 PM, Alberto Martinez <notifications@github.com<mailto:notifications@github.com>> wrote:


https://wysiwyg-editor.froala.help/hc/en-us/articles/115000555949-Can-I-insert-images-as-base64-

**Comment by AlverthoMartinez** [comment]
Well, thanks to the author! : )
