### ISSUE TITLE
Twitter Widget Issue

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1085]
Insert twitter widget and click right of it to it so cursor is blinking. Pressing enter removes widget instead of going to next line.

https://jsfiddle.net/f87p3s65/25/

**Comment by stefanneculai** [comment]
Actually this is not an editor issue, but it is highly related to the way of how Twitter Card is being embedded. The A tag is replaced with an IFRAME which has the content loaded through JS, it doesn't have any src set. Because of that when the line is split, the iframe content will go missing and you'll not see it anymore. Same thing will happen if you'll try to get the HTML inside the editor.
