### ISSUE TITLE
Add possibility for adding toolbar popups to the body

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#1098]
In older versions of your wysiwyg all toolbars were appended to the body.

Now there are appended to the toolbar. This is a bad idea. For example in my projects i have parent with limited width (and overflow: hidden too).
And i got the same situation: http://i.imgur.com/OSo20tT.png

Also i can have wysiwyg area very small (width)...

Please, provide any option to append those popups to the body as it was month ago...
Not only i have such issue...

**Comment by kotmatpockuh** [comment]
Is there any planed release date of this feature?

**Comment by stefanneculai** [comment]
No. We implement it based on how many requests are there for a feature and how important we consider it being. For the moment we have other features with higher priority.

**Comment by stefanneculai** [comment]
After a further check we decided that won't add this for two main reasons:
  1. The editor is positioning toolbars based on the `scrollableContainer` option. This means that inside the scrollableContainer everything should be visible.
  2. Having the popups appended to `body` instead of the toolbar wouldn't permit a smooth scrolling experience.
