### ISSUE TITLE
Images not proper dimensions

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1107]
##### Expected behavior.
img should display as the size specified

##### Actual behavior.
img width is being scaled down by 10px

##### Steps to reproduce the problem.
HTML is in textarea, can see that img width="90". Editor only shows width at 80.

##### OS.
All

##### Browser.
All

https://jsfiddle.net/f87p3s65/36/

**Comment by stefanneculai** [comment]
In CSS, there is the following rule `.fr-view img {max-width: calc(100% - 10px);}`. This prevents image to go larger than the editor width. Because you have a wrapper DIV, this rule would compute from the width of the DIV. The editor behaviour is correct. You could either change this rule to `max-width: 100%` or remove that wrapper DIV.
