### ISSUE TITLE
It's possible to add video via embed-code without protocol

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#1126]
##### Expected behavior.
Video is not inserted. Or video is inserted with default protocol.

##### Actual behavior.
Video is inserted (and 404 as result): 
http://i.imgur.com/PctJdPk.png
http://i.imgur.com/gusuLbn.png

##### Steps to reproduce the problem.
Try to insert youtube video code without protocol.

##### OS.
Windows 7.

##### Browser.
Chrome 48.

**Comment by stefanneculai** [comment]
It's not an issue. Inserting an iframe without a HTTP protocol tries to load the page from the current page which obviously won't work.

**Comment by kotmatpockuh** [comment]
It's an issue.
But ok, i remember the way you close all issues...

**Comment by stefanneculai** [comment]
Here are further details. Adding an iframe the way you want in a HTML page won't work. You can see that in the following the jsFiddle which doesn't use the editor: https://jsfiddle.net/froala/7usff17c/.

We have no reason why to close something that is an issue instead of fixing it and would appreciate a lot if you can collaborate with us. Thank you.
