### ISSUE TITLE
Inline toolbar and change style without selection

### ISSUE THREAD

**Issue by bionicvapourboy** [froala/wysiwyg-editor#1132]
##### Steps to reproduce the problem.
1. Setup a Froala editor instance with options  **toolbarInline: true** and **toolbarVisibleWithoutSelection: true**
2. Type something 
3. Select typed text and turn it bold
4. Deselect current selection clicking next to typed text **or** continue typing then click for get inline toolbar
5. Click Bold to disable it **or** use shortcut (cmd+B in my case)
6. Continue typing

##### Expected behavior.
Bold disabled for next keyboard inputs
Bold disabled in inline toolbar

##### Actual behavior.
Bold is still active as I type
Bold is still enabled in inline toolbar

##### OS.
OSX Maverick

##### Browser.
Chrome 49.0.2623.87

**Comment by stefanneculai** [comment]
Unfortunately, this is a `wontfix` for now because there is a WebKit issue and we can't do anything about it. It appears that Chrome has fixed it lately and it will be included in a release shortly (https://bugs.chromium.org/p/chromium/issues/detail?id=574363&q=label%3ACr-blink-layout&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified).
