### ISSUE TITLE
Odd cursor behavior and spaces being removed

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1176]
##### Expected behavior.
Cursor should stay on current line and spaces should not be removed

##### Actual behavior.
Cursor is flashing to the top and spaces between words are being removed

##### Steps to reproduce the problem.
http://jsfiddle.net/f87p3s65/70/
Click end of last line (whatsthedeal) and press enter until the cursor goes to the next time (usually takes twice)
start typing a sentence with spaces. the spaces are being removed and the words are being lumped into one. The cursor also keeps flashing to the top

##### OS.
Windows

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
This is caused by that empty `<span style="color: rgb(147, 101, 184);"></span>` and is a result of adding `SPAN` to `htmlAllowedEmptyTags`. As I explained on another issue, spans are sensitive tags in contenteditable and they might break things so it's always good to limit their usage. 

Also, having that `<span style="color: rgb(147, 101, 184);"></span>` is pretty useless because the browser will never put the cursor inside it and that's one of the reasons why the editor is removing empty spans by default.
