### ISSUE TITLE
Text Color Picker

### ISSUE THREAD

**Issue by alvarotrigo** [froala/wysiwyg-editor#1199]
##### Expected behavior.
Full text color picker or at least an hexadecimal color input box where the user can type the specific color they want. This will help people to use any color according to their own company palette or taste. 
An option for advance users would be ideal.

##### Actual behavior.
The developer is the one designing the color palette for the user and they can feel very restricted. More yet if the user cases are very different one from another. 

##### Steps to reproduce the problem.
Just try change the text color.

##### OS.
All

##### Browser.
All

**Comment by stefanneculai** [comment]
Thanks for the feedback, I truly appreciate it. The current color plugin works for most of our customers and if you are looking for something else it could be easily extended to something else. We got requests for allowing to enter their own hexa and we'll most likely add such a feature soon. I am closing this for now because we do not accept feature requests here on Github.

**Comment by kmacampbell** [comment]
Hi there, just wanted to add that many of our customers are also looking for a more flexible / full text color picker so happy to hear you're looking at adding this soon. Thanks!

**Comment by danielbentov** [comment]
Hi Stefan, When the custom color (hexa, rgbb) is planned? We have many customers that are waiting for it.

**Comment by kuzmany** [comment]
👍 for this request

**Comment by ursoforte** [comment]
Not wanting the topic, but see in https://github.com/ursoforte/colorhex

**Comment by spsarola** [comment]
@stefan some of our client not aware of hex value and its very difficult to pursued them
