### ISSUE TITLE
Merging span

### ISSUE THREAD

**Issue by ZeGregg** [froala/wysiwyg-editor#1201]
To keep dom lighter Froala should merge span instead of nest them

##### Expected behavior.
```
<p>
    <span style="color: rgb(97, 189, 109); font-size: 12px; font-family: Georgia,serif; background-color: rgb(41, 105, 176);">
        Test
    </span>
</p>
```

##### Actual behavior.
```
<p>
    <span style="color: rgb(97, 189, 109);">
    <span style="font-size: 12px;">
    <span style="font-family: Georgia,serif;">
    <span style="background-color: rgb(41, 105, 176);">
        Test
    </span>
    </span>
    </span>
    </span>
</p>
```

##### Steps to reproduce the problem.
Apply some style from home page example https://www.froala.com/wysiwyg-editor

**Comment by stefanneculai** [comment]
We had in V1 some methods for merging all these together. However, there were some cases when the performance dropped a lot and lots of reports of users who were not happy with this. We're currently doing some research on some alternatives to these. I will close, this because we don't keep feature requests here, but I can assure you that we're working on it. Thanks for the feedback!

**Comment by ZeGregg** [comment]
👍
