### ISSUE TITLE
Ignoring inline image css

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1216]
##### Expected behavior.
Should prioritize inline CSS as it has a higher specificity

##### Actual behavior.
Only applies Froala CSS classes and seems to ignore any inline style

##### Steps to reproduce the problem.
https://jsfiddle.net/f87p3s65/118/

##### OS.
Windows

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
First of all, there is a duplicate style attribute and the browser will render only the first one. When the editor is loaded, it converts inline CSS to classes and removes those properties which might be duplicate. There is a list of them: margin, float, display, z-index, position, overflow, vertical-align. This is the intended behaviour.

**Comment by rblin081** [comment]
I updated the fiddle revision, current only has one style attr

**Comment by stefanneculai** [comment]
That is the intended behaviour. It should remove margin and float and apply classes based on them. If you want not to have this happen, then you can remove the `imageDisplay` and `imageAlign` buttons from `imageEditButtons` option.

**Comment by rblin081** [comment]
I would think that the logic go the other way around. For newly created
content imageDisplay and imageAlign are desirable features that assist in
keeping consistent formatting. The issue comes from content that is already
fully formed. That content's formatting has already been established and
clearing styling creates unpredictable display results. Is there a reason
for a complete style overwrite vs filling in style when it is not there ?

**Comment by stefanneculai** [comment]
We are encouraging using classes over inline style for cleaner output. We start from the idea that any content that is loaded inside the editor should have been previous edited with the editor. Of course, there might be cases when the content might come from other places where it was edited with other editor, but in that case it would be migrated to how Froala Editor works. We are following this behaviour since the very first version of the editor and we believe this is the way to go.
