### ISSUE TITLE
Selecting and deselecting cells in table freezes editor

### ISSUE THREAD

**Issue by mrjlynch** [froala/wysiwyg-editor#1265]
##### Expected behavior.
Selecting and deselecting cells in table shouldn't freeze editor

##### Actual behavior.
Selecting and deselecting cells in table shouldn't freezes editor
![githubnew](https://cloud.githubusercontent.com/assets/3665457/15274162/ba097a16-1aef-11e6-9be4-1c5f261be7d7.gif)

##### OS.
Mac OS X

##### Browser.
Chrome

**Comment by dianaprajescu** [comment]
Selecting multiple cells in a table should freeze the editor for multiple reasons:
1. The editor toolbar buttons have no meaning for the current selection;
2. We want to select cells and to achieve this we need to prevent text selection;
3. In order to have the same cell selection behaviour in all browsers, Froala comes with a custom cell selection tool. For this reason, we need to prevent default cell selection from various browsers when `contenteditable="true"`.

However, when selecting only one cell, the editor toolbar shouldn't freeze. I'm not able to replicate this. Is there something else, except left click, that you are pressing? Are you using the latest master version? Our website (https://froala.com/wysiwyg-editor) doesn't use the latest version from Github until we make a new release.

**Comment by mrjlynch** [comment]
This is replicable on the [froala homepage](https://www.froala.com/wysiwyg-editor) using Chrome, Firefox & Safari. I am not pressing any buttons at all. 

I have not tried to replicate this on the master branch.

**Comment by dianaprajescu** [comment]
Yes, it can be replicated on our homepage, because it doesn't use the latest version from master until a new release is made.

This is cannot be replicated on the latest master version from Github. Please try the master branch and let me know is you can replicate it there. Closing this until then.
