### ISSUE TITLE
[v.2.2.4] how to disable adding extra classes "fr-dib fr-draggable" to images?

### ISSUE THREAD

**Issue by sunra** [froala/wysiwyg-editor#1270]
If i insert image via Image button, Froala editor added **class="fr-dib fr-draggable"** to img tag.
How to disable this?

**Comment by stefanneculai** [comment]
To remove draggable you should disable imageMove option. To remove fr-dib you should not include the imageAlign and imageDisplay buttons inside imageEditButtons option.

**Comment by sunra** [comment]
fr-dib not removed :(
I use this settings.
```
{   
   pastePlain: true,
   heightMin: 200,
   imageMove: false,
   imageEditButtons: ['imageRemove', '|', 'imageLink', 'linkOpen', 'linkEdit', 'linkRemove', '-',  'imageAlt', 'imageSize'],
   imageInsertButtons: ['imageBack', '|', 'imageUpload', 'imageByURL']
}
```

**Comment by stefanneculai** [comment]
If you already have fr-dib in the HTML you initialize the editor with it, it won't be removed. You'd have to use a regex for that.

**Comment by sunra** [comment]
I not have fr-dib already. I reload page with empty editor and insert image with imageInsertButtons imageUpload

**Comment by stefanneculai** [comment]
Are you using the master version or an older version?

**Comment by sunra** [comment]
v.2.2.4

**Comment by stefanneculai** [comment]
Last commit updates this behaviour. Additionally to removing those buttons, you should set `imageDefaultAlign` and `imageDefaultDisplay` to `null`.

**Comment by sunra** [comment]
used version: 2.2.5
config:
```
{
                        language: 'ru',
                        placeholderText: 'Начните свой шедевр здесь',
                        pastePlain: true,
                        heightMin: 200,
                        imageMove: false,
                        imageEditButtons: ['imageRemove', '|', 'imageLink', 'linkOpen', 'linkEdit', 'linkRemove', '-',  'imageAlt', 'imageSize'],
                        imageInsertButtons: ['imageBack', '|', 'imageUpload', 'imageByURL'],
                        imageDefaultAlign: null,
                        imageDefaultDisplay: null
                    }
```

i insert image and result is:
```
<p><img class="" src="http://i.froala.com/download/d8e918d5ba15e80f4cba0ef47b2ccd16be45e59a.jpg?1463588007" style="width: 300px;"></p>
```

***class=""*** - what is confused me. Can editor not to add this?

**Comment by sunra** [comment]
Yes it solved!

I see similar problem with **style=""**

**Comment by Neha2900** [comment]
Hi,
 While generating a report in word ,  extra classes such as fr - dib fr- fill get added to the styling of the  images I have inserted in the editor , this creates an issue for me resulting in a bad formatting .
I want the exact css  to be applied to the image while generating report.

![image](https://user-images.githubusercontent.com/28554933/46471161-b8bbd580-c7f6-11e8-9005-d9991515b760.png)

This is the case where I want my image to be adjusted in a column of a table, but because of the froala classes it results in bad formatting.


Desirable Result - 

![image](https://user-images.githubusercontent.com/28554933/46471266-ff113480-c7f6-11e8-84f6-41049993f211.png)

**Comment by Neha2900** [comment]
Hello,
I have used the  Properties Specified above.The Alignment of images and content is perfect in the Web Layout View but still I am facing the issue enlisted above in the Print Layout View in Word.
For Reference
Web Layout - 
![image](https://user-images.githubusercontent.com/28554933/48707607-f8fbd980-ec25-11e8-910f-754bc5bb23ed.png)
Print Layout - 
![image](https://user-images.githubusercontent.com/28554933/48707639-14ff7b00-ec26-11e8-924f-0a9184768abe.png)

Please Help me with this issue.

**Comment by abhishekparidaadl** [comment]
Hi Sunra,

Please update me on the issue raised by Neha on Nov 19th.

The adviser is really waiting for the alignments to be fixed asap.

Please update us at the earliest.

**Comment by abhishekparidaadl** [comment]
Hi Sunra, 

It has been 26 days till to date where I haven't received any response from you.

Please let me know what has been the progress of the issue we have reported to you 19th Nov, 18.

Till date we have not received any response from you. Are you working on the issue or not ?

We need a timely response from your end, such delays of more than 2 months isnt serving our purpose of using your editor. We really need some concrete steps to be taken from your side to avoid such delays.

Looking eagerly for your response.

**Comment by stefanneculai** [comment]
@Neha2900 @abhishekparidaadl it looks the problem you have is not related to this issue. Also, please explain what is the problem you are facing in more details and the steps to reproduce it.

**Comment by Neha2900** [comment]
Hello Sunra,
The Problem I am facing in froala editor is because of  inserting images,
As I insert image in the editor, css of the image is overwritten by the extra classes of images of froala editor, this creates an issue for me even I have disabled them and that content I am rendering in a table format, when it get renders because of the styling of the image the alignment gets disturbed as I download that word document in print layout.
**Steps to Reproduce**
1. Add an image and content in editor.
2. The content is desired in a table format while downloading the document.

**Comment by abhishekparidaadl** [comment]
@sunra 
Please see the above response from Neha on the issue we have reported.

Please investigate on this and update us.

Awaiting your response.
