### ISSUE TITLE
Unable to backspace from one line to another

### ISSUE THREAD

**Issue by rblin081** [froala/wysiwyg-editor#1298]
##### Expected behavior.
When backspacing at beginning of line, should bring up to next line

##### Actual behavior.
Pressing backspace does nothing

##### Steps to reproduce the problem.
http://jsfiddle.net/f87p3s65/136/
put cursor before Thursday and press backspace. No action will happen

##### OS.
Windows

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
This is an unusual case which the editor won't deal with because you have `H3` which is a block tag inside a `SPAN` which is a markup impossible to generate using the editor. Also such markup is not W3C valid and it will generate an error when you try to [validate it](https://validator.w3.org): `Element h3 not allowed as child of element span in this context`.
