### ISSUE TITLE
Pasting an image in the editor returns a 404

### ISSUE THREAD

**Issue by asifhussain60** [froala/wysiwyg-editor#1302]
##### Expected behavior.
pasting the image would call the server side action

##### Actual behavior.
Server returns a 404

##### Steps to reproduce the problem.
I'm trying to paste an image into the editor. I have the options configured as (taken from the MVC sample of server integration)

imageUploadURL: '/api/doc/image',  // I've also tried the full path of http://localhost/api/doc/image
imageParams: { postId: 123 },

This URI points to a WEB API 2 controller (ASP.NET 4.5)

[HttpPost]
        [Route("api/doc/image")]
[HttpPost]
        public IHttpActionResult FroalaUploadImage(HttpPostedFileBase file, int? postId) // نام پارامتر فايل را تغيير ندهيد
        {
            var fileName = Path.GetFileName(file.FileName);
            //var rootPath = Server.MapPath("~/images/");
            //file.SaveAs(Path.Combine(rootPath, fileName));

            return Ok(Json(new { link = "images/" + fileName }));
        }

I keep getting back a 404 error. I've ensured that the URI is accurate by connecting to it using a separate page

##### OS.
Windows 10

##### Browser.
Chrome50.x

**Comment by stefanneculai** [comment]
404 means that the image could not be found at the returned URL. It is not an editor issue, but something related to your server side integration. We use GitHub Issues as the official bug tracker for the Froala WYSIWYG HTMl Editor. For questions or help integrating the editor please [contact us](https://www.froala.com/wysiwyg-editor/contact) instead of opening an issue.
