### ISSUE TITLE
Bullet appears when editing code

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1392]
Visit http://jsfiddle.net/2Ldek60e/
Switch to code view
Insert another "x" after the first
Once you add the second "x", a weird bullet shows up:

<img width="328" alt="screenshot 2016-07-06 15 55 05" src="https://cloud.githubusercontent.com/assets/97612/16632444/24d83bfa-4392-11e6-8e02-83fa9b714f66.png">

OS X Chrome 51.0.2704.103

**Comment by stefanneculai** [comment]
To me this looks like a problem from Chrome browser and not something coming from the editor. See https://jsfiddle.net/cvwq3td5 and with the fix for it https://jsfiddle.net/cvwq3td5/1/. I just reported it to their bug tracking repo and waiting for a response: https://bugs.chromium.org/p/chromium/issues/detail?id=626293.

In the meanwhile, I would recommend to use the clearfix approach for the inner element.
