### ISSUE TITLE
Destory doesn't unbind events

### ISSUE THREAD

**Issue by nozpheratu** [froala/wysiwyg-editor#1444]
Seems calling the destroy method on feField will remove the editor, but not unbind events. Manually calling `unbind()` on the FE field is required. Specifically the `save.before` event doesn't seem to get unbound.

**Comment by stefanneculai** [comment]
Would it be possible to create a jsFiddle to highlight this? We tried to reproduce it, but without success.

**Comment by nozpheratu** [comment]
Here we are https://jsfiddle.net/j0h1q1qL/
Seems even after I do `$('.edit').froalaEditor('destroy');` the node still retains some event bindings.

**Comment by stefanneculai** [comment]
@nozpheratu It appears you're using an older version `v2.0.0-rc.3`. The current one is `v2.3.4`.

**Comment by nozpheratu** [comment]
Whoops. Here it is with the current version: https://jsfiddle.net/1t9auzd0/

**Comment by Panman8201** [comment]
Just looking through some of the eventing ATM. IMO the original functionality is "correct". I think if someone binds an event listener outside of the editor instance then it should be up to them to remove the event listener. Ex:

```js
var contentChangedHandler = function(){};
var $editor = $('.editor');
$editor.froalaEditor();
$editor.on('froalaEditor.contentChanged', contentChangedHandler);
$editor.froalaEditor('destroy');
$editor.off('froalaEditor.contentChanged', contentChangedHandler);
```

But if the event handler is applied via the [editors method](https://www.froala.com/wysiwyg-editor/docs/methods#events.on) then they should be removed by the editor instance when destroyed. Ex:

```js
var contentChangedHandler = function(){};
var $editor = $('.editor');
$editor.froalaEditor();
$editor.froalaEditor('on.event', 'contentChanged', contentChangedHandler);
$editor.froalaEditor('destroy'); // listener removed "automatically"
```

FWIW, this is a breaking change for the `ember-froala-editor` addon, since event listeners are [applied once when the element is inserted](https://github.com/froala/ember-froala-editor/blob/master/addon/components/froala-editor.js#L198).

**Comment by Panman8201** [comment]
Because the addon attaches the listeners once, on render, but the editor may be destroyed and re-initialized within the life of the rendered element. It's a technicality that I'll need to work around.

**Comment by stefanneculai** [comment]
You could bind those events in the initialized callback of the editor for instance.
