### ISSUE TITLE
List bullets or numbers do not change color when associated text is changed

### ISSUE THREAD

**Issue by cricci** [froala/wysiwyg-editor#1497]
##### Expected behavior.
When text color is changed, the bullet (or number) should change color to match.

##### Actual behavior.
Bullet doesn't change color. Text does.

##### Steps to reproduce the problem.
1. Enter some text
2. Highlight some or all of the text and make it bulleted (or into an ordered list)
3. Highlight some or all of the bulleted text and change its color. Ex:

![screen shot 2016-09-06 at 3 01 23 pm](https://cloud.githubusercontent.com/assets/1062266/18289049/63e7a2f4-7443-11e6-8c31-8e1d851f3921.png)

##### OS.
Mac OSX

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
We consider this as being a `wontfix` because browsers do not permit to change the color of the bullet only without the rest of the text inside the LI element.

**Comment by cricci** [comment]
I think you misunderstand. We want the bullet and text to be the same color. As it is, when we Change the text color (for any one or all LI), the bullet(s) does (do) not change to match.

**Comment by stefanneculai** [comment]
@cricci I understood it correctly. However, it's not possible to change the color of those bullets because the browser do not allow to change the color of the bullet only in lists.

**Comment by carolynmills** [comment]
@stefanneculai would this be the same for font size of the number in the case of an ordered list?

**Comment by stefanneculai** [comment]
@carolynmills yes, it is the same for font size of numbers for OL.

**Comment by nico-onmap** [comment]
I am having the same problem.

The thing is that froala applies the color to a `<span>` that gets added to each `<li>`:

```html
<ol>
	<li><span style="color: rgb(209, 72, 65);">degreztert</span></li>
	<li><span style="color: rgb(209, 72, 65);">fhdfhhdf</span></li>
	<li><span style="color: rgb(209, 72, 65);">fdhdfh</span></li>
</ol>
```

So the color isn't applied to the bullets.

If there was a way to select and apply the color to the list only, like this it would fix the problem:

```html
<ol style="color: rgb(209, 72, 65);>
	<li>degreztert</li>
	<li>fhdfhhdf</li>
	<li>fdhdfh</li>
</ol>
```

Note that first selecting a color, then creating a new list produces the same code, applying the color to the `<span>` instead of the `<li>`.

**Comment by stefanneculai** [comment]
@nico-onmap that would introduce some problems when changing the style afterward for parts of the list. We're working on some improvements here.

**Comment by prasadk24** [comment]
Hi @stefanneculai 
any update on this. do you any solution

**Comment by dianaprajescu** [comment]
If you make changes that affect only selected text, instead of the entire paragraph, then those changes will not affect the bullets of a list.

However, if you use for example the `Paragraph Styles` plugin, then the selected style will apply on the entire list item, therefore making the bullet have the same style as the text. Here is an example from our website where e have a predefined paragraph style called Gray, and you can see that using it will change the bullet as well:

<img width="1234" alt="Screenshot 2019-04-10 at 12 42 00" src="https://user-images.githubusercontent.com/1551136/55871639-c1210e80-5b93-11e9-9953-ddd190ae9a61.png">

**Comment by JohnTheis** [comment]
If you wanted to keep it as is, you can change the display property of the spans to 'list-item'. Just need to add the code below:
`.fr-view {
	ul {
		list-style: none;

		li {
			span {
				display: list-item;
				list-style-type: disc;
			}
		}
	}
}`

**Comment by JohnTheis** [comment]
If you wanted to keep it as is, you can change the display property of the spans to 'list-item'. Just need to add the code below:

`.fr-view {
	ul {
		list-style: none;

		li {
			span {
				display: list-item;
				list-style-type: disc;
			}
		}
	}
}`

**Comment by JohnTheis** [comment]
If you wanted to keep it as is, you can just change the spans to list items with a few lines of custom CSS:

`.fr-view ul {
     list-style: none;
}`
`.fr-view ul li span {
     display: list-item;
     list-style-type: disc;
}`

**Comment by Pi-Solution** [comment]
Hello guy I had the same problem and I needed fix so I created small script so for those who have the samo problem here is the script.

        // Added execution after windows is loaded
        window.addEventListener('load', function () {

            // you can use class and "for loop" instead of id if you have more than one wysiwyg on page
            let yourWysiwyg = document.getElementById('your-wysiwyg-id')

            let list = yourWysiwyg.getElementsByTagName("li")

            for (let i = 0; i < list.length ; i++) {

                list[i].style.color = getComputedStyle(list[i].childNodes[0]).color

            }
         })
