### ISSUE TITLE
Twitter embed in Code View

### ISSUE THREAD

**Issue by themoor88** [froala/wysiwyg-editor#1575]
##### Expected behavior.

When I copy and paste the embed code from Twitter, the code view should retain all the code I pasted. Not remove the blockquote, p and a tags. I am using the rails plugin for Froala. https://github.com/froala/wysiwyg-rails
##### Actual behavior.

When I click save on my editor and then click on code view again, the only thing remaining from the twitter embed is the twitter script tag. So after I click save, the twitter embed disappears.
##### OS.

Version 10.12, MacOS Sierra
##### Browser.

Chrome Version 53.0.2785.143 (64-bit)

**Comment by stefanneculai** [comment]
@themoor88 could you please send us what you're pasting in code view?

**Comment by themoor88** [comment]
I am copying and pasting the twitter embed code, for example, something like this 
```<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Lord plz tell me why Gaga is dressed like a Nazi.. 🙏🏻🙄 <a href="https://t.co/Gd2nAxySD8">https://t.co/Gd2nAxySD8</a></p>&mdash; Jessica (@SpaitoGaming) <a href="https://twitter.com/SpaitoGaming/status/795874364164083713">November 8, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>```

**Comment by stefanneculai** [comment]
When you embed this in the editor, the script from Twitter is changing the blockquote into their own HTML structure. That structure is then removed by the editor in code view because those are not allowed HTML tags (see htmlAllowedTags and htmlAllowedAttrs). Instead of doing that you should embed only the Twitter blockquote and then when you display the HTML add the script from Twitter on your page.

**Comment by themoor88** [comment]
Thanks.
