### ISSUE TITLE
Paste Word, PDF sometimes removes some spaces throughout the content - EDGE Browser

### ISSUE THREAD

**Issue by DenisaSurdu** [froala/wysiwyg-editor#1655]
Following #1167 , the issue seems to persist when using the editor in Edge.

##### Steps to reproduce the problem.
- Open https://www.froala.com/wysiwyg-editor using Edge.
- Remove the pre-populated text
- Go to https://www.ucl.ac.uk/amyloidosis/pdfs/nac_newsletter_1
- Copy the fist paragraph from the PDF and paste it in Froala editor (Edge browser)
- Notice some words lack spacing (see below screenshot as well). 

![image](https://cloud.githubusercontent.com/assets/4330214/20839465/9c8e0b66-b8a4-11e6-8c43-df714a427ce0.png)

##### OS.
Windows

##### Browser.
EDGE: Microsoft Edge 38.14393.0.0 & Microsoft EdgeHTML 14.14393

**Comment by stefanneculai** [comment]
@DenisaSurdu what PDF viewer are you using?

**Comment by YannLeBihan** [comment]
Hi,

Was about to post the exact same issue for Mac/Safari. PDF viewer is Safari itself.

**Comment by YannLeBihan** [comment]
Hi @stefanneculai ,

I think this issue should be reopened. Attached is a Word file with two random sentences, created on a Mac running macOS 10.3.4  with Word's latest version (16.12 180410). If you copy/paste the whole text from Word to Froala's home page demo editor on Safari 11.1, here is the result :

![capture d ecran 2018-04-19 a 12 36 47](https://user-images.githubusercontent.com/6142093/38986948-6365c476-43ce-11e8-93b4-d939d2e1e63f.png)

As you can see, some words are glued together, just like in the example @DenisaSurdu posted for Edge. The problem doesn't occur on Chrome, and is clearly not related to the Word paste plugin since the gluing happens with or without it.

[Test Froala Word paste.docx](https://github.com/froala/wysiwyg-editor/files/1927711/Test.Froala.Word.paste.docx)
