### ISSUE TITLE
Can't write in input created in the edit image popup

### ISSUE THREAD

**Issue by FletcherPink** [froala/wysiwyg-editor#1671]
##### Expected behavior.
I need to add "unknown yet class" to image. So i create a button who insert HTML text input and its validation button in the "edit image popup". This button will add value to image data-attribute.

##### Actual behavior.
I can do the focus in the input but can't write in it. 

##### OS.
El Capitan / Froala 2.4.0

##### Browser.
Firefox 50.1.0

Thank You

**Comment by stefanneculai** [comment]
This doesn't look like an editor problem, but rather an implementation issue. We offer tech support via our website for users who have a license that includes support. Please reach us through there: https://www.froala.com/wysiwyg-editor/contact.

**Comment by FletcherPink** [comment]
I am sorry to insist but the editor prevents writing in a dynamically created input field by clicking a button in the image editor. If I move this input field out of the popup (.fr-popup.fr-desktop.fr-ltr.fr-active) the input works. This is not an implementation issue.

**Comment by jdigz** [comment]
I'm experiencing the same issue. What seemed to solve it for me was there was a tabindex conflict. My Froala editor was inside of a Bootstrap Modal and the Modal has tabIndex=-1. Removing that in the developer tools allowed the input to work.

After some investigating here is the full explanation.
Bootstrap modals have tabindex="-1", role="dialog" and aria-modal="true" set for accessibility. What these do is make only what is in the Bootstrap Modal keyboard accessible.

The issue here is that Froala is appending the popup to the body of the document which falls outside of the Bootstrap Modal making the inputs not focus-able due to the accessibility attributes the Bootstrap Modal div.modal has (listed above). This means that you can't focus any inputs within the froala popup in these cases.

**Comment by jdigz** [comment]
Here is another explanation with a proposed solution where tinyMCE had the same troubles [tinyMCE Issue 5169](https://github.com/tinymce/tinymce/issues/5169)
