### ISSUE TITLE
html.get returns unexpected result when option editInPopup is set to true 

### ISSUE THREAD

**Issue by tyclipso** [froala/wysiwyg-editor#1683]
##### Expected behavior.
Content of editor

##### Actual behavior.
Content of editor and HTML of the editor-container

##### Steps to reproduce the problem.
https://codepen.io/f39462/pen/BQqBgO

There you 2 editors. If you set some text, you will see different results. The first one is unexpected.

##### OS.
Windows 10

##### Browser.
Chrome 55

**Comment by stefanneculai** [comment]
This is the default behavior for all other custom types of elements: `img, input, button`. It is implemented this way because many users are looking to extend the behavior and also add attributes to the element on which the editor was initialized. If you are looking for a custom behaviour, you could use the following code to get only the content of the element the editor was initialized on:

```js
$(selector).data('froala.editor').$oel.html();
```
