### ISSUE TITLE
Can't remove blockquote by using backspace

### ISSUE THREAD

**Issue by mattiaslundberg** [froala/wysiwyg-editor#1691]
##### Expected behavior.
The blockquote is removed when pressing backspace

##### Actual behavior.
Nothing happens

##### Steps to reproduce the problem.

1. Open https://jsfiddle.net/11csLex6/4/
2. Place marker before B inside the blockquote
3. Press backspace to remove the blockquote

##### OS.
Any OS.

##### Browser.
Any browser.

**Comment by stefanneculai** [comment]
This was initially marked as an issue, however at a closer check, it appears that the behavior is correct. You have the the following structure:
```html
<div class="wrap3 fr-inner">
  <blockquote>
     <p class="inner">Blockquote inner text.</p>
  </blockquote>
</div>
```
Since you're using the `fr-inner` class, that doesn't allow to make changes outside of them. They are like a black box and allow editing only inside them. 

Also, the editor is designed to split the `blockquote` in two when you hit enter inside them. That is the behavior we consider as being correct.

**Comment by docikaci** [comment]
@mattiaslundberg  hi  
https://jsfiddle.net/11csLex6/4/
@stefanneculai 
How to solve it? I found that the removal of the three div can be deleted, or press Ctrl can also be deleted!
