### ISSUE TITLE
The events are delayed

### ISSUE THREAD

**Issue by monolithed** [froala/wysiwyg-editor#1771]
##### Example

```css
.editor {
	font-size: 14px;

	&--scale {
		& .fr-element {
			font-size: 24px;
		}
	}
}
```

```ts
import * as React from 'react';
import * as ReactBlock from 'react-bem-helper';
import bind from 'bind-decorator';
import Editor from 'react-froala-wysiwyg';
import { Constants } from './constants';
import './index.css';

export interface Props { }

export interface State {
	modifiers?: {
		[name: string]: boolean
	};
}

class Compose extends React.Component<Props, State> {
	constructor () {
		super();

		this.state = {
			disabled: false,
			modifiers: {}
		}
	}

	private block = new ReactBlock({
		name: 'editor'
	})

	@bind
	contentChanged (event: KeyboardEvent, editor) {
		let size: number = editor.charCounter.count();

		this.setState({
			modifiers: {
				scale: size > 5
			}
		});
	}

	render () {
		let block = this.block({ modifiers: this.state.modifiers });

		return <div { ...block }>
					<Editor tag='textarea' config={
						{
							placeholderText: 'Enter your text here!',

							events : {
								'froalaEditor.contentChanged': this.contentChanged
							}
						}
					}/>
				</div>;
	}
}

export default Compose;
```

##### Actual behavior.

Very very slow

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here)

##### OS.
macOs, Chrome

Maybe the problem in `react-froala-wysiwyg`, I don't know, but it should be investigated. 
Please use my example to reproduce the problem.

![hkbrdjsxki](https://cloud.githubusercontent.com/assets/803674/23095400/77ec3978-f61a-11e6-964d-77d3f48d5950.gif)

**Comment by stefanneculai** [comment]
This is the correct behavior as the `contentChanged` event is not designed to be triggered immediately but only when the user makes a pause while typing. This is mainly for performance reasons.

**Comment by robclancy** [comment]
The 250ms limit on this has caused us issues. We have many areas which are hidden until input but it feels buggy to the user if they type a sentence and the whole form doesn't show until they stop. IMO the debounce should only be for internal stuff but the `contentChanged` event should be instance or with a separate, much faster debounce. Looking at the code the `contentChanged` event is part of the undo buffer which seems weird.

Another example is a field with a error that makes it red, but when they type the red it meant to go away. Once again this will be delayed. This editor should function like a textarea with superpowers but instead it acts like it is on a server and you have to wait for the server.

250ms is also too long. Default of 500ms is way too long as can be seen in this issue (pretty much always press a button and get a "this is required" error because 500ms hasn't passed yet.

Anyway going to hack it to have no minimum and set to 100ms.

(this comment is a mess because I edited lots based on what I read)
