### ISSUE TITLE
[Feature proposal] Image caption

### ISSUE THREAD

**Issue by pkhruasu-ui** [froala/wysiwyg-editor#1828]
Due to my work related's task I had to extend image capabilities to be able to add image caption.
So far I belive that I am able to do that and cover most of the side effects that occur.

So to my question, how do I hand off this change to Froala team so that they can take a look and, if possible, fix any oversight and integrate it into the official plugin?

Ex: 
![image](https://cloud.githubusercontent.com/assets/6283085/23807862/439ffd96-057c-11e7-8d54-c59cce735c0d.png)

![image](https://cloud.githubusercontent.com/assets/6283085/23807878/554d6c7c-057c-11e7-8572-0196dd9ef5eb.png)

**Comment by stefanneculai** [comment]
Thank you for the suggestion. Image figure is on our TODO list already. We do not keep feature requests here on Github, therefore I am closing it for now.

**Comment by pkhruasu-ui** [comment]
Oh that is great to know it is on TODO list. Is it possible to tell when this feature is available?

**Comment by stefanneculai** [comment]
We don't have an ETA for it at this moment.

**Comment by Floriskoch** [comment]
@pkhruasu-ui would you mind sharing your work? I'm looking to build similar functionality, thanks!

**Comment by pkhruasu-ui** [comment]
@Floriskoch here is the file. It is v2.4.2.
[froala-image-caption-2-4-2.txt](https://github.com/froala/wysiwyg-editor/files/1125622/froala-image-caption-2-4-2.txt)

**Comment by stefanneculai** [comment]
Just a quick update here. The last commit is adding image caption feature.

**Comment by pkhruasu-ui** [comment]
Perfect. Thanks so much for letting use know. How do we add it?

**Comment by stefanneculai** [comment]
Just update to version 2.7.0 and you'll find it in the Image Edit popup. There is also a demo on our website: https://www.froala.com/wysiwyg-editor.

**Comment by pkhruasu-ui** [comment]
Perfect. Many thanks and great jobs!!

**Comment by aaclayton** [comment]
Hi Froala, thanks a lot for adding image caption support, however, I am wondering why you did not opt to use a more semantic HTML specification for the elements. For example (using the demo on the website)

```
<p style="text-align: center;"><span class="fr-img-caption fr-fir fr-dii" style="undefined"><span class="fr-img-wrap" style="width: 200px;"><img width="200" src="https://cdn0.froala.com/assets/editor/pages/B/editor-photo-645d411798e5b4e825765d091dd5aaab.jpg" alt="Editor photo"><span class="fr-inner">This is a caption</span></span>
	</span>
</p>
```

It seems to me that this should have been done by using the `figure` and `figcaption` semantic elements, instead of awkwardly using `span` for everything. For example, something like:

```
<p style="text-align: center;">
    <figure class="fr-img-caption fr-fir fr-dii">
        <img width="200" src="https://cdn0.froala.com/assets/editor/pages/B/editor-photo-645d411798e5b4e825765d091dd5aaab.jpg" alt="Editor photo">
        <figcaption class="fr-inner fr-caption">This is a caption</figcaption>
    </figure>
</p>
```

Do you have some intuition for why relying on `<span>` instead of more semantic elements is the best way to go?

Thanks,
Andrew

**Comment by dianaprajescu** [comment]
Sure, @aaclayton. Using `span` instead of `figure` is quite a debated topic, both internally and among Froala Editor users. Please check out issue #2206 for more details.

**Comment by aaclayton** [comment]
Hi @dianaprajescu, thanks for the link, was informative. I understand having read the related ticket why the span decision was made, and I'm glad to hear that `<figure>` support will be considered for a future major version. 

One possible approach might be to add a configuration option to the image plugin that would allow the user to chose their caption style without forcing existing users into the change. Obviously, adding conditional support increases code complexity, but it might be a good way to collect more data before making a final decision.

**Comment by jEnbuska** [comment]
Any update on this?

**Comment by shnigi** [comment]
Any update on this?

**Comment by mattbartel** [comment]
I'd like to re-up this request. Having at least the option to use the semantic figure and figcaption tags would be a big help for those of us using CSS frameworks like [Bootstrap](https://getbootstrap.com/docs/5.2/content/figures/) or [Tailwind](https://tailwindcss.com/docs/typography-plugin), which both rely on those tags to format images properly. 

As was noted in [#2206](https://github.com/froala/wysiwyg-editor/issues/2206), using figure tags creates unpredictable behavior when inside a p tag, but in my opinion, there are fewer use cases for in-paragraph images than stand-alone images. 

Not being able to edit the DOM produced by the image plugin creates a pretty big headache for those of us that just need simple, standardized images between paragraphs. Currently there isn't even an easy way to assign a default width based on percentage rather than pixels. 

Thanks for the consideration.

**Comment by sqwk** [comment]
Is there an update on this? Or alternatively a workaround, plugin that performs image insertion using `figure` and 
`figcaption` elements?
