### ISSUE TITLE
Content Security Policy Violation With style-src Requires unsafe-inline

### ISSUE THREAD

**Issue by dalezak** [froala/wysiwyg-editor#1946]
##### Expected behavior.
Using [wysiwyg-rails](https://rubygems.org/gems/wysiwyg-rails) and [secure_headers](https://github.com/twitter/secureheaders) with `style_src: %w('self')`, the Froala editor is causing an violation with `style-src` due to inline styles.

##### Actual behavior.
_Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' fonts.gstatic.com". Either the 'unsafe-inline' keyword, a hash ('sha256-iECgl+DQnRhCoJAZvXsuvD/twj/lAfgSGNGuDV8nJs0='), or a nonce ('nonce-...') is required to enable inline execution._

##### Steps to reproduce the problem.
Looks like this line in particular is causing an issue.
```
tmp.innerHTML = wrap[ 1 ] + jQuery.htmlPrefilter( elem ) + wrap[ 2 ];
```

##### OS.
Rails 5 using the `wysiwyg-rails` gem.

##### Browser.
Chrome Version 57.0.2987.133 (64-bit)

**Comment by stefanneculai** [comment]
@dalezak Indeed, there are some CSS style which are applied inline, however they are required in order to enable rich features. Positioning UX elements require setting left/top CSS properties and setting the style inline is the most convenient way.

**Comment by dalezak** [comment]
Is there a way to include `sha256-` or `nonce-` in the Froala editor config?

The error message suggests these as an option to enabling `unsafe-inline`. 

_Either the 'unsafe-inline' keyword, a hash ('sha256-iECgl+DQnRhCoJAZvXsuvD/twj/lAfgSGNGuDV8nJs0='), or a nonce ('nonce-...') is required to enable inline execution._

**Comment by stefanneculai** [comment]
As far as I know, that wouldn't be possible because the editor would require to apply dynamic CSS properties such as top/left and those are always different.

**Comment by pkundariya** [comment]
Hi Guys,

I have issue with uploading image to editor from long time. i am not finding any solution could anyone please help me out to this?

My Server is NGINX so please give solution according it. Thanks

I am using Froala Editor. When trying to drag and drop image to upload in editor i see below error message.
![image](https://user-images.githubusercontent.com/37189926/37167612-60c7c604-2328-11e8-91dc-3e74160f6ace.png)

In Console Error Message is:

Refused to load the image 'blob:https://www.example.com/831a7599-7b0c-416c-ab79-7678f2409e7d' because it violates the following Content Security Policy directive: "default-src https: data: 'unsafe-inline' 'unsafe-eval'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

Could you please help me to resolve this?

Thank you in advanced
Parth
