### ISSUE TITLE
Letter spacing sets multiple spans 

### ISSUE THREAD

**Issue by delian7** [froala/wysiwyg-editor#2104]
##### Expected behavior.
Ideally every time `editor.format.applyStyle('letter-spacing', "#em")`, it wraps everything in a span and/or updates the span. 

##### Actual behavior.
Multiples spans are created and wrapping the content. We have a slider on our website and this results in multiple spans. 

##### Steps to reproduce the problem.
Refer to this [codepen](https://codepen.io/delian7/pen/RoGdLp?editors=1111): 

1. Open console and click "GET HTML".
2. Select all.
3. Click "Letter Spacing 0.1em", "Letter Spacing 0.2em", "Letter Spacing 0.3em", etc.,
4. Click "Get HTML"

##### OS.
macOS 12

##### Browser.
Chrome v59

**Comment by delian7** [comment]
@stefanneculai I understand that your team is working on this. Do you have a method that would detect unused span and do a cleanup as a workaround to this issue?

**Comment by stefanneculai** [comment]
@delian7  We don't have a workaround for now.

**Comment by delian7** [comment]
@stefanneculai thanks for the quick response. Not to be pushy, just for our planning purposes would you possibly know how big of an endeavor this would be? Would you have an ETA?

**Comment by stefanneculai** [comment]
It is a particular case for applying the inline styles, and the change required for this has quite a lot of implications. Unfortunately, I cannot tell an ETA at this moment.

**Comment by delian7** [comment]
@stefanneculai do we have an updated ETA on this issue? It is getting kinda pressing for us since we cannot update to the latest version of Froala.

**Comment by delian7** [comment]
@stefanneculai can I expect this issue to be resolved or should I look for a workarounds?

**Comment by dianaprajescu** [comment]
@delian7 I apologize for not having an answer for you for such a long time. We've tried multiple times to find a fix for this, but the truth is that version 2 of the editor was not designed to work with `em`. We will make sure this is not going to happen in V3.

Until then, there is a workaround, but it comes with a compromise. We cannot fix this issue and also keep the correct order for issue #2081 that you reported. Currently, the editor will never create such an output (like the one from issue #2081), but it did happened some time ago, in the beginning of V2. That code was generated a long time ago with the editor and that's why you had such code in the editor in the first place.

We would really appreciate your input on this before taking any decision about the approach we should take. Thanks in advance!

**Comment by delian7** [comment]
hi @dianaprajescu, thanks for the reply and happy new year! 

ahh, issue #2081. That was unfortunately something that our customers were complaining about. and were seeing quite frequently. Perhaps we can get a hacky workaround for when Froala wrap the selection in a DOM element, to unwrap it first. I'm not a fan of this too much though because of the hackiness. 

Without ripping out the fix for #2081, do you see a workaround that we can even do going forward? Since I made the issue, we transitioned our sliders to an input field with up and down arrows, so less wrapping should occur as a result of this issue. Bu still our text HTML can get pretty long if customers use the up/down arrows since Froala wraps the DOM elements.

**Comment by stefanneculai** [comment]
@delian7 unfortunately, without making changes to #2081 it wouldn't be possible to address this. The inline styles weren't designed with EM in mind and that's why it's not possible to extend the functionality, but it should be made from scratch.

**Comment by delian7** [comment]
hi @stefanneculai i understand.
