### ISSUE TITLE
Expectation of a <label> tag?

### ISSUE THREAD

**Issue by Panman8201** [froala/wysiwyg-editor#2115]
##### Expected behavior.
Using a `<label>` targeting a `<textarea>` (turned Froala Editor) should focus the editor.

##### Actual behavior.
Editor is not focused

##### Steps to reproduce the problem.
I've created a JS Fiddle replicating this, along with a label that attaches an event handler to focus the editor. My question is; should the editor support this out of the box somehow? Or is this not a supported scenario?

https://jsfiddle.net/Panman8201/dg0mmz87/ 

##### OS.
Windows 10

##### Browser.
Google Chrome

**Comment by stefanneculai** [comment]
@Panman8201 we reviewed this, and we believe that is a bit out of the editor scope because of the way `for` works in the browser. Your solution is a more suitable one.

**Comment by vkoves** [comment]
@stefanneculai - Although it is not possible (as far as I have been able to figure out) to make a `<label>` change focus to the editor, it is possible to properly associate one with the editor by having the Froala `.fr-element.fr-view` have an ID that can be targeted, or have the editor use `aria-labelledby`.

I have created a JSFiddle based off of @Panman8201's that uses some additional Javascript to add an to the Froala view to make it so that the focusing the Froala editor actually reads out the label text. However, this seems like a hack, and something that I think should be exposed through Froala settings. Here's the fiddle: https://jsfiddle.net/vkoves/tszw2mah/

Is there already a good way of setting an ID or aria properties onto the actual Froala element that gets focus, so we don't have to do these Javascript overrides after Froala has rendered to implement proper labels? Without these hacks, we cannot make our Froala editor usage compliant to [WCAG 2.0 Success Criterion 3.3.2 - Labels or Instructions](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=332#labels-or-instructions).

**Comment by stefanneculai** [comment]
@vkoves do you think you could ask for this feature on https://wysiwyg-editor-roadmap.froala.com?

**Comment by vkoves** [comment]
@stefanneculai - certainly, just did that.

**Comment by Dan503** [comment]
It really isn't that difficult to add label support.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/textbox_role

```html
<div id="txtboxMultilineLabel">Label text goes here</div>
<div
  role="textbox"
  contenteditable="true"
  aria-multiline="true"
  aria-labelledby="txtboxMultilineLabel"
  aria-required="true"
></div> 
```
