### ISSUE TITLE
Inline image with left align overlaps bullets/numbers of ordered/unordered list

### ISSUE THREAD

**Issue by raerae13** [froala/wysiwyg-editor#2143]
##### Expected behavior.
When there is an ordered or unordered list to the right of a left aligned inline image, the styling for the involved elements needs to allow the bullets or numbers to be visible.

##### Actual behavior.
The image ends up overlapping the bullets or numbers. The text still displays.

##### Steps to reproduce the problem.
On Froala website home page. Make the visible text a bulleted list. Then change the already inline image to be left aligned. See attached video.

##### OS.
Windows 10 Pro

##### Browser.
Chrome Version 60.0.3112.90 (Official Build) (64-bit)

[left aligned image and bullets.zip](https://github.com/froala/wysiwyg-editor/files/1222919/left.aligned.image.and.bullets.zip)

**Comment by stefanneculai** [comment]
@raerae13 unfortunately, because of the way browsers are displaying elements we don't have a fix for this. One possible workaround would be to add the following CSS, however, we don't want to add it by default in the editor because it would change the way lists are designed to work by default in the browser.

```css
.fr-view ol, .fr-view ul {
  list-style-position: inside;
}
```
