### ISSUE TITLE
How to avoid multiple paste event calls

### ISSUE THREAD

**Issue by peca11** [froala/wysiwyg-editor#2149]
##### Expected behavior.
I'm trying to find a way to prevent users from making multiple paste event calls in a row when the past content is big (like a wiki page), which can lead to the browser becoming slow or unresponsive.

I have tried to use the froala paste methods to stop multiple calls but I cant make it work.
I also tried to catch the "paste" event with document.addEventListener ("paste... but the code just ignores it.

##### Actual behavior.
It seems that only one paste calls is processed at the time.
So this means I can't use the froala paste methods to prevent the stacking of paste calls.
Is there a way to prevent stacking paste request when a paste event is in progress with the current code ?

##### Steps to reproduce the problem.
Open this page and copy all the content (ctrl+a and then ctrl+c) - https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style#Italics
Open a page with a froala editor, select the editor and past the content a couple of times in a row, like 5 to 10 (ctrl+v)
I understand this is an extreme example, but I'm just making a point that there should be some sort of protection against this sort of behaviour from the user. 

##### OS.
Win 10 

##### Browser.
Chrome - 60.0.3112.101

**Comment by stefanneculai** [comment]
@peca11 this is rather related to how the browser works rather than the editor. If you'd try to paste the same content in a `contenteditable="true"` element, then the browser would keep pasting several times. If you would like to prevent that in the editor, you could use the `paste.before` and `paste.after` events to cancel other pasting actions being done. However, it might be possible that the browser keeps them in a stack and fires another one just after the first paste has finished.
