### ISSUE TITLE
Touch scrolling on editor toolbar buttons does not work as expected in Android

### ISSUE THREAD

**Issue by mikesul** [froala/wysiwyg-editor#2153]
This is an extension off the change from #2146 - unfortunately, this fix/improvement is not complete and there are now differences between iOS and Android.

##### Expected behavior.
When touch a touch starts on an editor toolbar button and you drag away from it, the page should be allowed to scroll.

##### Actual behavior.
The page doesn't scroll and despite the touch ending off the button, the formatting of the button is sometimes applied.

##### Steps to reproduce the problem.
Can be reproduced here: https://www.froala.com/wysiwyg-editor Put the editor near the bottom of the viewport and attempt to scroll down the page by initiating the touch on one of the editor toolbar buttons.

##### OS.
Android. Based on code, potentially Windows Phone as well. iOS is not directly affected due to the part of the issue being code they do not trigger.

##### Browser.
Tested in Chrome 59 on Android. It is possible to reproduce in Chrome on the desktop if you enable the device toolbar and set the preset to an Android phone.

I had sent a patch through to fix this issue a while back. I can recreate it against 2.6.5 if needed. The fix for #2146 only changes one area of the patch. There are really only 2 other changes that are needed:

1. Android and WP both get the touchstart event prevented. This prevents the scroll from happening. I haven't noticed any side effects of disabling this code, but I'm not aware of the issue that lead to it.
2. The dragging detection doesn't appear to be sufficient. For touchmove events, it seems to trigger if the move lasts for more than 100ms, though that's very easy to not trigger. I would propose logging where the touchstart happens (clientX/clientY) and checking that when touchmove is triggered. If the distance ever goes over a certain threshold (say, 10px), then trigger the dragging behavior.

**Comment by stefanneculai** [comment]
Unfortunately, in order to have the buttons work correctly, it is necessary to prevent the scroll event on them for the Android OS. While I can see how this affects the UX, it is the best solution we could find to use the buttons without losing the selection inside the editor. It appears that on Android even the slightest move of the finger when tapping a button triggers the scroll event and sometimes the browser fires the `scroll` event before the `touchstart` one.

For now, I am going to close this and mark it as `wontfix`. We might review it on further major editor version. However, we're not going to change this behavior in the current major version V2.

**Comment by steffenweber** [comment]
First of all, thank you for this awesome WYSIWYG editor!

I think Froala is a great user-experience overall but unfortunately (and to be completely honest) as an Android user this issue is annoying: When half of the screen is covered by the keyboard, making a signifcant part (two button rows) of the other half unusable for scrolling, too, feels bad. Could you maybe have a second look at this problem?

Maybe more recent Chrome versions don't lose the selection anymore (as you described) if you don't "preventDefault" the `touchstart` listener?

Maybe setting the CSS property [touch-action](https://developer.mozilla.org/de/docs/Web/CSS/touch-action) on the toolbar could help?

Is there a Chrome bug report about this issue?

**Comment by stefanneculai** [comment]
@steffenweber thanks for the suggestions, we'll look into them.

**Comment by Lee1984** [comment]
I believe this is solved now
