### ISSUE TITLE
Can't delete At.js autocomplete variable with backspace

### ISSUE THREAD

**Issue by natcohen** [froala/wysiwyg-editor#2194]
Go here: https://codepen.io/anon/pen/wrBaGa write @ and choose one selection.

The chosen selection can't be either selected (with mouse) or deleted with backspace or even be "navigable" with the arrows of the keyboard (and therefore can't be editable). The default behaviour should be this http://ichord.github.io/At.js/

**Comment by sandeepsukhija** [comment]
@stefanneculai even we are facing the same issue when froala editor is integrated with the latest At.js ver 1.5.4.

It works well with the version 1.4.0 as integrated and showcased in the https://www.froala.com/wysiwyg-editor/examples/at-js

**Comment by stefanneculai** [comment]
@natcohen @sandeepsukhija we've just updated the CodePen. https://codepen.io/Froala/pen/ZeZzEN

**Comment by natcohen** [comment]
@stefanneculai Thanks! How if we'd like to be able to edit the inserted atwho? In the example here: http://ichord.github.io/At.js/ you can edit the variable. For example, if you write smile and select it, you can still navigate with your arrow inside the variable ('smile') and edit it. In your example, you can't navigate inside the variable.

In addition, when deleting with the backspace, it deletes the whole variable while the atwho example deleted only letter by letter and offer a new auto complete.

Could you please provide a full example with the exact same behavior as the main example of the atwho website?

**Comment by stefanneculai** [comment]
@natcohen on the example from ichord, they appear to be using an older version, not the latest one. You should be able to get that behavior with version 1.4.0 or similar.

**Comment by natcohen** [comment]
@stefanneculai Ok, thanks for the info! Will stick with the new version...

**Comment by bobbino** [comment]
Hi @natcohen, how did you solve it? I got your same issue. Any suggestion is very appreciated. Already tried with version 1.4.0

**Comment by natcohen** [comment]
No, I just luve with it...

**Comment by TheBigK** [comment]
I'm looking for a fix as well. I've integrated this with Froala, but now backspace just won't work. Would really appreciate a quick fix.

**Comment by loutocky** [comment]
If you want to navigate inside variable, this works for me (froala + at.js)

`private froalaInitializedEvent(atJsconfig: Object): Object {
    return function (e, editor) {
      editor.$el
        .atwho(atJsconfig)
          .on('inserted.atwho', function () {
            // we need to edit also text, which was added by autocomplete
            editor.$el.find('.atwho-inserted').removeAttr('contenteditable').removeAttr('data-atwho-at-query');
        })

      editor.events.on('keydown', function (e) {
        if (e.which == $.FroalaEditor.KEYCODE.ENTER && editor.$el.atwho('isSelecting')) {
          return false;
        }
      }, true);
    }
  }`

**Comment by chicofaccin** [comment]
Hi.
We are having a problem in Firefox, We can't delete at.js autocomplete variable with backspace. I saw that this bug report was closed. But the problem comes back at version 2.8.0, only in Firefox. It's possible to see the problem here -> [https://codepen.io/chicofaccin/pen/QxGLMJ?editors=1111](https://codepen.io/chicofaccin/pen/QxGLMJ?editors=1111)

![screenshot from 2018-06-07 15-21-07](https://user-images.githubusercontent.com/1117150/41230725-40405440-6d57-11e8-87c4-b4180db552f9.png)

Now, with the version 2.7.4, the bug doesn't happen. 
-> [https://codepen.io/chicofaccin/pen/PabYxB?editors=1111](https://codepen.io/chicofaccin/pen/PabYxB?editors=1111)

Feel free to reach out if you need any further details. We have an OEM license.
Regards,
