### ISSUE TITLE
Internal "paste as plain text" pastes formatted text

### ISSUE THREAD

**Issue by Tade0** [froala/wysiwyg-editor#2223]
##### Expected behavior.
Pasted text is not formatted.

##### Actual behavior.
Pasted text is formatted.

##### Steps to reproduce the problem.
1. Go to https://www.froala.com/wysiwyg-editor.
2. Select a part of the text, apply "bold" and copy.
3. Using the context menu paste it somewhere else inside the editor.

##### OS.
Windows 7, Ubuntu.

##### Browser.
Chrome 60.0.3112.113, 61.0.3163.100

**Comment by stefanneculai** [comment]
@Tade0 are you able to reproduce it here? https://www.froala.com/wysiwyg-editor/examples/plain-paste

**Comment by Tade0** [comment]
In the link you provided regular paste(obviously) doesn't work.

What I need is for both formatted text and plain text pasting to work.

**Comment by stefanneculai** [comment]
@Tade0, when plainPaste is enabled, all the content is designed to be pasted like this. It doesn't matter if it comes from the editor or from outside. We consider this as being the intended, correct behavior for this option.

**Comment by Tade0** [comment]
Ok, but what I want is for both formatted text and plain text pasting to work when the plainPaste plugin is _not_ enabled.

**Comment by rajchetan** [comment]
@Tade0 were you able to solve this.

**Comment by stefanneculai** [comment]
@Tade0 @rajchetan this should work as you suggested in the latest 2.7.5 version.

**Comment by Tade0** [comment]
@stefanneculai Ok, thanks for the info.

**Comment by gabrielduchon** [comment]
Hi, I have the same issue in Froala Editor 3.0.5

Actual behavior, expected behavior, steps to reproduce the problem the same as above by Tade0. One more example with the actual editor: https://jsfiddle.net/5v7azr89/6/

**OS.**
Mac, 10.12.6.

**Browser.**
Chrome, Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by gabrielduchon** [comment]
@stefanneculai 

Hi, I have the same issue in Froala Editor 3.0.5

Actual behavior, expected behavior, steps to reproduce the problem the same as above by Tade0. One more example with the actual editor: https://jsfiddle.net/5v7azr89/6/

**OS.**
Mac, 10.12.6.

**Browser.**
Chrome, Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by draek** [comment]
Has there been any updates to this issue. Froala latest v3 still pastes Formatting when plainPaste is turned on. We need a true plain paste, no font sizes, no tags, no html of any kind. Is this not achievable?
