### ISSUE TITLE
The imageUploadRemoteUrls should default to false

### ISSUE THREAD

**Issue by dswitzer** [froala/wysiwyg-editor#2323]
Since the `imageUploadRemoteUrls` can send images to Froala servers, I suggest the default behavior of the `imageUploadRemoteUrls` option should be `false`. 

Unless a person reads the documentation carefully, I think it's easy to miss that images may get proxied to https://cors-anywhere.froala.com which can lead to security concerns.

If the `imageUploadRemoteUrls` was defaulted to false, then this does not happen.

Users can always enable this option if they need the functionality.

**Comment by stefanneculai** [comment]
@dswitzer most of the users want to have images which are inserted via an URL to be uploaded to their own server. `imageUploadRemoveUrls` option is being used only for helping the upload of images inserted via an URL and images inserted this way are public on the Internet anyway because if they wouldn't be public you couldn't access them. Images which go on `https://cors-anywhere.froala.com` are being deleted in a matter of minutes as they are the CORS service is using a Heroku Server just as described on https://github.com/Rob--W/cors-anywhere.

**Comment by dswitzer** [comment]
IMO, the security aspect of this is super critical. I think most users would be surprised that images being pasted are being passed through your servers. And well you may be deleting them, what if that changes? What if there's a bug and the files are being wiped? 

I think it's great you're offering the service, but it should be something users **opt-in** to, not something that just happens. At a bare minimum, I think it has to be **extremely** clear that this is going to happen. I think most users upgrading from 2.7.0 to 2.7.1 would be surprised to find images might be getting sent to your servers.

**Comment by stefanneculai** [comment]
Thanks for the feedback, @dswitzer. I just checked the code of the `cors-anywhere` [lib](https://github.com/Rob--W/cors-anywhere) and it actually doesn't download the image, but just makes a proxy for the CORS, so that the image can be accessed via JS. For now, we'll keep it like this and change that if there is another feedback.
