### ISSUE TITLE
IE11 clicking unlink with cursor at end of link fails

### ISSUE THREAD

**Issue by bryannovoed** [froala/wysiwyg-editor#2331]
##### Expected behavior.
With the cursor at the end of a link, clicking unlink unlinks the link and clears out the toolbar.

##### Actual behavior.
With the cursor at the end of a link, clicking unlink does not unlink the link and leaves the toolbar in weird state.

##### Steps to reproduce the problem.
1. Go to https://www.froala.com/wysiwyg-editor/examples/inline
2. put the cursor at the end of "toolbarinline"
3. Click unlink in the link toolbar
![ie_unlink](https://user-images.githubusercontent.com/8356554/32567958-bb0883a8-c471-11e7-8270-a1fff4401057.gif)

##### OS.
Windows 8.1

##### Browser.
IE11

**Comment by bryannovoed** [comment]
probably a related issue. sometimes when clicking at the end of a link on ie. the toolbar doesn't show all options 
![ie_end_of_link](https://user-images.githubusercontent.com/8356554/32757947-e22aaa3c-c896-11e7-91a5-041132c2ab40.gif)

**Comment by stefanneculai** [comment]
We decided to disabled showing the link popup at the beginning/ending of links because, in IE, the selection changes at around 200ms after the `mouseup` event and this causes the link to be returned incorrectly. Unfortunately, this is the best workaround at this moment.

We also made [a jsFiddle](https://jsfiddle.net/jredzam3/) which highlights this situation from IE: click at the end of `foo` text and watch the browser console.

**Comment by bryannovoed** [comment]
@stefanneculai we noticed that this was disabled for mobile as well. in iOS this presents a potential problem for users since iOS tends to place the cursor at the beginning or end of words. so if the link is only 1 word long. the user has to know the force the cursor in the middle of the word by forcing the cursor magnifying glass. any particular reason for changing it on mobile as well?
