### ISSUE TITLE
Froala Image storage

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2349]
hi,

I am using Froala advance image option, I noticed that its uploading images on froala server, I want to ask after purchasing froala where will image be uploaded? or is there any way that we can store images on our servers as for now its returning Blob object which only contains image size and type but no link of image, same for image by url option.

I also noticed that advance image option is opeing from http://cd.aviary.com, every time its giving a hit to this url, after purchasing will its library be provided? or our application will continue to hit on these servers, same for Wiris ?

Regards

**Comment by stefanneculai** [comment]
By default, the editor uploads the images and files to our servers so that you can test how the editor works right away. However, they are stored there only temporary and might be deleted at anytime. We do strongly recommend to change this and upload it to your own server. Please read more about that on our website:
https://www.froala.com/wysiwyg-editor/docs/concepts/image-upload. 

The Advanced Image options is using Adobe Aviary ad that's why there is a request made over to Aviary for processing the image.

**Comment by javeriaanwer** [comment]
Our requirement was to store images on our servers , we achieved this in Froala but not able to use Advance Image option, throwing error that images are not public, what should be the work around as we can not put our images in public folder.

**Comment by stefanneculai** [comment]
@javeriaanwer the Advanced Image editor is an integration for Adobe Aviary. For the advanced image processing, yes, it is required to hit the Adobe servers.
