### ISSUE TITLE
Copy Pasting issues from different docs and Font Size misinterpretation

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#2360]
There are issues with the copy pasting of words from different documents to the Froala editor. Following issues were observed.

**Word Document :** 
- Copy Pasting of words that are formatted to the editor invokes the word plugin but clean does not work.
- The Font Size shown in the editor doesn't align with word's font size.

**Power Point :**
- Selecting Clean doesn't clear the formatting while copy pasting and same issue with the font size

**PDF :** 
- No Prompt , just clears the formats present in the words , doesn't  recognize line spacing.

**Excel :**
- Copy the entire cells and selected clean , but the grids also get copied.
- Copied direct content from the cell , no prompts this time and auto defaulted to clear formatting

**Html :**
- Copied contents got pasted and and got defaulted to clean formatting

**Font Size was not displaying correctly** always varies from that showed in docs and editor. 
Thanks in Advance.

##### Steps to reproduce the problem.
Above said issues can be tried out in the Froala Editor present in the site itself

##### OS.
Windows 7 

##### Browser.
Chrome 62.0.3202.94 (Official Build) (64-bit)

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV it would be really helpful if you could send us the documents to copy/paste from. Thanks in advance.

**Comment by ShanmugaPriyanV** [comment]
@stefanneculai Attached the test documents for your assistance.
[Froala_Format_Testing_PDF.pdf](https://github.com/froala/wysiwyg-editor/files/1498515/Froala_Format_Testing_PDF.pdf)
[Froala_Format_Testing_PPT.pptx](https://github.com/froala/wysiwyg-editor/files/1498516/Froala_Format_Testing_PPT.pptx)
[Froala_Format_Testing_WordDocument.docx](https://github.com/froala/wysiwyg-editor/files/1498517/Froala_Format_Testing_WordDocument.docx)
[Froala_Format_Testing_ExcelSheet.xlsx](https://github.com/froala/wysiwyg-editor/files/1498518/Froala_Format_Testing_ExcelSheet.xlsx)

**Comment by stefanneculai** [comment]
@ShanmugaPriyanV we just tested this and we don't consider the problem as being from the editor:
- Word and PowerPoint: the font size is kept, however, the font family used by Word is Calibri and that's why it might look different in the browser. 
- PDF: this is the way we get data from the clipboard. Unfortunately, there is nothing we can do about it.
- Excel: Pasting from Excel creates a table. This is the correct behavior. When pasting directly from a table cell, we don't get the formatting in clipboard, so there is nothing we could do about it.
- HTML: looks fine.
