### ISSUE TITLE
Validators required

### ISSUE THREAD

**Issue by P-Hayk** [froala/wysiwyg-editor#2408]
I built separated module for editor...
imported that module in my component and using it...
besides I have form with validation created by reactive forms...
Please help to add validation in editor?? and it isn't  important to do that via reactive forms..

**Comment by stefanneculai** [comment]
@P-Hayk the best way to add validations to the editor is to get the HTML using `html.get` method and validate that HTML output.

**Comment by P-Hayk** [comment]
I did it like this..
  <textarea formControlName='textEditor' [froalaEditor]="options"></textarea>
without using another module..thanks

**Comment by stefanneculai** [comment]
@P-Hayk please see the example from Github for reactive forms: https://github.com/froala/angular-froala-wysiwyg#model.

**Comment by LexBel-co** [comment]
Hi, the workaround in  https://github.com/froala/angular-froala-wysiwyg#model does not accomplish the reactive form validation, because the code "form.valid" is always "false" even with data into de Froala Editor, how can we solve this? It only works if the page is reloaded, it seems that angular doesn't bind the value to the form control

Sample form:

`<form [formGroup]="form">
    <div [froalaEditor]="configFroala" formControlName="text"></div>

    <button [disabled]="!form.valid"
            (click)="save(form.value)"> 
        Save
    </button>
</form>`
