### ISSUE TITLE
Parsing response failed when uploading image

### ISSUE THREAD

**Issue by michaelezehi** [froala/wysiwyg-editor#2436]
Hi ,

When I try to upload an image to our server I get this error (Parsing response failed) 
Please see the screenshot below: 

![image](https://user-images.githubusercontent.com/10596765/34154150-6f7cdab4-e4ac-11e7-8fd7-13c48ed19ee3.png)

With this displayed in the view:
![image](https://user-images.githubusercontent.com/10596765/34154439-729d9fac-e4ad-11e7-905a-d930653e1abe.png)

Please we really need help with this. 

Why is this error coming up. Our URL is not currently reachable as this is a test environment and can only be accessible through DNS.

Thanks for your help

**Comment by stefanneculai** [comment]
That is because the response format is not correct. It should be a json like this:

```json
{ "link": "path/to/image.jpg" }
```

**Comment by tomzi** [comment]
Hi,
I am using the last version of Froala v3.0.6 and i followed the documentation to upload files by settings the JS params like : 
 - imageUploadURL
 - imageUploadParams
 - imageUploadMethod
 - imageMaxSize
 - imageAllowedTypes

```
var editor = new FroalaEditor('#NewUpdateForm_NewUpdateForm_Content', {
        toolbarInline: false,
        language: 'fr',
        attribution: false,
        imageUploadParam: 'image_param',
        imageUploadURL: $("#NewUpdateForm_NewUpdateForm").data("upload-file-link"),
        imageUploadParams: {id: $("#NewUpdateForm_NewUpdateForm_ID").val()},
        imageUploadMethod: 'POST',
        imageMaxSize: 25 * 1024 * 1024,
        imageAllowedTypes: ['jpeg', 'jpg', 'png'],
```

In the PHP part :
Once my file is uploaded i return the absolute url wrapped in a JSON object
```
$response = new StdClass;
$response->link = Director::absoluteBaseURL() . "" . $file->Filename;
return stripslashes(json_encode($response));
```
The problem is i got the parsing file error each time
`{code: 4, message: "Parsing response failed."}`

Could you please help me ?
Thanks

**Comment by RomansSapsan** [comment]
Check content type of your response. With Laravel, for me, it allways was: "text/html". In Laravel You should manualy define it like: 

 return response()->json([
            'link' => '/upload/image.png',
        ]);
