### ISSUE TITLE
Unable to insert empty tags

### ISSUE THREAD

**Issue by BakuDev** [froala/wysiwyg-editor#248]
It's impossible to insert empty html tags like:

`<div class="clear"></div>`
`<td></td>`

Editor is deleting 'em and breaks html structure.

**Comment by mklemme** [comment]
Can we add an option to override this line in the froala editor.js?: `$element.find('div:empty:not([class])').remove();` It is removing the empty divs served from the db before I even have the chance to add the whitespace char.

**Comment by stefanneculai** [comment]
There is no option for that. However, you could override the wrapTextInElement method to change that.

**Comment by julieushpa** [comment]
@stefanneculai's suggestion doesn't seem to work. if i add a zero width space into the tag it gets converted into a break, which is exactly what i don't want.
```
<div style="clear:both">&#8203;</div>
```
is converted into
```
<div style="clear:both"><br>
</div>
```

any other ideas?

**Comment by stefanneculai** [comment]
@julieushpa the initial comment was for V1 of the editor and many things have changed since then. However, if you'd use the master version (866fd83e724e1b505a487f28dd4175e882528cbb), then all you should do is to add the `contenteditable` attribute: `<div style="clear:both" contenteditable="false"></div>`.

**Comment by julieushpa** [comment]
@stefanneculai - Thanks for the quick response. It's taken a while to get updated (due to unrelated issues), but the contenteditable style doesn't work to suppress insertion of the <br>. I confirmed that even in the version on the official website it doesn't work (with or without the zero-width space): https://www.froala.com/wysiwyg-editor

Is there some flag that needs to be turned?
