### ISSUE TITLE
Clicking 'X' on Code insertion window causes browser is completely freeze

### ISSUE THREAD

**Issue by dragokas** [froala/wysiwyg-editor#2516]
##### Expected behavior.
Click button 'Insert' on Editor's BB-code panel -> Code -> Click 'X' (in bottom right corner) -> should close the window.

##### Actual behavior.
Browser is completely freeze ([SafeZone.cc](https://safezone.cc/threads/interceptor-ng.30077/) forum)

##### Steps for reproducing:
You can login with this account:
Login: terminator2
Pass: Alex_Qwerty

##### OS.
Win 7 x64 / x32

##### Browser.
[Opera Presto 12.18](http://get.geo.opera.com/pub/opera/win/1218/int/Opera_1218_int_Setup_x64.exe)

**Comment by dianaprajescu** [comment]
@dragokas we don't really understand Russian, is this the window you are talking about?

<img width="897" alt="screen shot 2018-01-24 at 21 08 26" src="https://user-images.githubusercontent.com/1551136/35351841-d9146324-014a-11e8-81f5-746c4ad71fbe.png">

**Comment by dragokas** [comment]
Yes, it is.

You can also reproduce it on xenforo.com, but I can give you login/pass if only you send me something like email or so.
I am curious, GitHub has no PM system.

**Comment by dianaprajescu** [comment]
First of all, this window is not part of the Froala Editor. There probably is an issue with the code you have for it that is not related to the editor.

Secondly, we just tested this in Windows 7, Opera 50 (the latest version) and it is working okay. We are only supporting the current last version of Opera and the one before it. Here is a list with supported browsers for the Froala Editor: https://www.wired.com/2013/02/presto-is-dead-long-live-opera/.

We strongly recommend you to upgrade your browser especially because Opera dumped Presto 5 years ago (https://www.wired.com/2013/02/presto-is-dead-long-live-opera/) and it seems that the latest Presto update was 3 years ago.

**Comment by dianaprajescu** [comment]
Forgot to mention: if the window that is not closing is from the xenForo software, then you should contact them.
