### ISSUE TITLE
Missing Translation (DE)

### ISSUE THREAD

**Issue by divdax** [froala/wysiwyg-editor#2522]
Editor is used with german language. The paragraph styles are still in english:

<img width="193" alt="bildschirmfoto 2018-01-26 um 16 06 23" src="https://user-images.githubusercontent.com/1456739/35445838-30aa1322-02b3-11e8-8dac-b96875e76bab.png">

### Translation
```
Gray      = Grau
Bordered  = Umrandet
Spaced    = Zeichenabstand
Uppercase = Großschreibung
```

**Comment by dianaprajescu** [comment]
@divdax the options that you have in the paragraph styles are only for demo purposes and that's why they are not translated. The values that are there by default are just an example of how the plugin works and what can be done with it.

Normally, you should define your own styles (that integrate with your website's design) and replace the defaults with your custom ones.

Another example would be the inline style plugin. For demo purposes, the default values are `Big Red` and `Small Blue`. I assume you are not going to use those.
