### ISSUE TITLE
Problem with http://formvalidation.io/

### ISSUE THREAD

**Issue by CTorres18** [froala/wysiwyg-editor#2661]
Froala don´t work with the formvalidation properties.
For example don´t work with the 'threshold' property, any way to fix it?

**Comment by stefanneculai** [comment]
Because of the way formvalidation.io works, it is not possible to call directly on the editor field. That's why a workaround is required, as described in https://github.com/froala/wysiwyg-editor/issues/1251#issuecomment-218478754. It looks like formvalidation.io isn't taking into consideration the `threshold` property when the `revalidateField` method is called.
