### ISSUE TITLE
Quote missing class fr-selection

### ISSUE THREAD

**Issue by nemiq** [froala/wysiwyg-editor#2662]
Quote-button is missing css class "fr-selection". This becomes an issue if button width is reduced:

```
.fr-toolbar .fr-command.fr-btn,
.fr-popup .fr-command.fr-btn {
..
width: 30px;
..
}

.fr-toolbar .fr-command.fr-btn i,
.fr-popup .fr-command.fr-btn i,
.fr-toolbar .fr-command.fr-btn svg,
.fr-popup .fr-command.fr-btn svg {
..
  margin: 8px 8px;
..
}

.fr-toolbar .fr-command.fr-btn span,
.fr-popup .fr-command.fr-btn span {
..
  min-width: 30px;
..
}
```

My quick fix for now is:
```
$('#question').on('froalaEditor.initialized', function (e, editor) {
   editor.$tb.find('[data-cmd="quote"]').addClass('fr-selection');
}).froalaEditor()
```

**Comment by stefanneculai** [comment]
@nemiq thanks for reporting this. We've just checked it again and the quote button is designed not to have a display selection as the other buttons have there because it includes 2 actions, but no state. If you'd like to display a text for the quote, we'd recommend to do it like this just before initializing the editor:

```js
$.FE.COMMANDS.quote.displaySelection = function () {
  return 'Quote';
}
```

**Comment by nemiq** [comment]
@stefanneculai I'm not trying to add any text, I'm just trying to shrink the overall button size (all buttons displayed). If I change the CSS as mentioned above then only the Quote button won't change, as a result it starts overlapping the next button.
