### ISSUE TITLE
Can we Add our content in multiple pages as Google docs

### ISSUE THREAD

**Issue by vartikatomaradl** [froala/wysiwyg-editor#2689]
##### Expected behavior.
(Allow user to add content in multiple pages instead of a single page)

##### Actual behavior.
(Currently we have a single page in editor, we don't have any page break facility or any plugin)

##### Steps to reproduce the problem.
(Is it possible to break editor page into multiple pages like google docs. For Example: https://docs.google.com/document/d/1fLBLMkKe6pJKX1otiSTs9cwbrbSQ2snmDTbEgKZ_pzU/edit)

##### OS.
(Any)

##### Browser.
(Any)

**Comment by stefanneculai** [comment]
We don't have a page editing mode yet, however, it is on our `feature-list`.

**Comment by vartikatomaradl** [comment]
Can you please provide an approx date for this feature to be included in froala editor?

**Comment by davidalejandroaguilar** [comment]
+1, this would be immensely helpful for generating documents.

**Comment by karanjariwala** [comment]
+1, We have recently bought froala and are looking for a way to add page breaks in the document.

**Comment by alan-albuquerque** [comment]
Hi, I have a project that generates a document in the browser, just like Google Docs. This option would be great! Is this feature being considered?

**Comment by asafwat** [comment]
Any updates on this feature?

**Comment by stefanneculai** [comment]
It is on our roadmap: https://wysiwyg-editor-roadmap.froala.com/public/ideas/5916

**Comment by jhchill666** [comment]
+1, long road map, 2 and a half years :(

**Comment by herbertharriola** [comment]
3 and a couple months after and the functionality is not added.....

**Comment by MRH136** [comment]
4 years and couple months without any updates !!

**Comment by ignaraph** [comment]
Currently im handling this by using the html.insert method of froala to insert an `<img />` element that has these css classes:
-border:1px dashed #aaa;
-display:block;
-width:100%;
-height:5px;
-margin-top:15px;
-page-break-before:always;

I include the border so that the user has a visible feedback of where the page break was inserted.

Personally using the html2pdf library to convert the file to pdf, before creating the pdf im parsing the html and replacing the border color from #aaa to transparent. Works like a charm

Hope this helps someone
