### ISSUE TITLE
Code view formatting with 2.7.6

### ISSUE THREAD

**Issue by TwentyOverTen** [froala/wysiwyg-editor#2712]
##### Expected behavior.

If you go into code view and enter the following code:

```
<div class="something">
    <ul>
        <li>something else</li>
    </ul>
</div>
```
When you toggle back and forth between code view and editor, the code is formatted with a break, such as:

##### Actual behavior.
```
<div class="something">

    <ul>
        <li>something else</li>
    </ul>
</div>
```

##### OS.
Mac

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
@TwentyOverTen when displaying the code view, based on the plugins that you might be using, Code Beautifier / Code Mirror, there might be a couple of indentation changes. Also, the editor is designed to make some changes in order to assure the best editing. Unfortunately, in the current version V2, we won't make any changes to that.
