### ISSUE TITLE
License terms?

### ISSUE THREAD

**Issue by rudolfolah** [froala/wysiwyg-editor#2717]
It looks like the code is available for everyone to see this and yet the license terms are proprietary? :|

If it's proprietary, why is the code for the sdk and integrations up here at all. A bit ridiculous.

**Comment by stefanneculai** [comment]
We use this repo mainly for bug tracking. While the editor is paid, you can download it for free and take for a spin before purchasing the license so that you can make sure it works for your needs.

The SDKs and framework integration plugins are licensed under MIT / BSD. These licenses apply only for the code of the integrations, not the editor itself.

**Comment by rudolfolah** [comment]
thanks for the clarification!

it's just strange that the license.txt is so sparse and doesn't mention MIT/BSD: https://github.com/froala/wysiwyg-editor/blob/master/License.txt

**Comment by stefanneculai** [comment]
The framework plugins are under the MIT/BSD license, not the editor itself: https://github.com/froala/angular-froala-wysiwyg, https://github.com/froala/react-froala-wysiwyg, etc.
