### ISSUE TITLE
IE11: Browser crashes when inserting an image after entering a specific character string

### ISSUE THREAD

**Issue by da-yamashita** [froala/wysiwyg-editor#2770]
##### Expected behavior.
Images can be inserted

##### Actual behavior.
Browser crashes.

##### Steps to reproduce the problem.

 1. Insert ("あ" + line break) * 5 times, like bellow.

あ
あ
あ
あ
あ

 2. Move the mouse cursor to the right of the first "あ" and insert the image.

* "あ" is Japanese Character.

 3. Browser crashes.

Even Japanese characters behave differently depending on the number of lines and letters.

 * It does not reproduce when inserting ("あ" + line break) * 4 times
 * It reproduces when inserting ("亜" + line break) * 5 times
 * It does not reproduce when inserting ("飯" + line break) * 5 times

##### OS.
Windows10

##### Browser.
IE11(It does not reproduce with chrome）

**Comment by agwidarsito** [comment]
Are you able to supply a Fiddle? Even if I cannot help I can try and confirm it's happening for me too.

**Comment by da-yamashita** [comment]
Hi agwidarsito, Thank you.

"Fiddle" means JsFiddle?

*It reproduces on the Froala official website.

**Comment by stefanneculai** [comment]
@largeden could you please confirm if you're able to reproduce this? Thanks in advance!

**Comment by stefanneculai** [comment]
I just checked this and works fine on my side with the current master repo. @largeden do you think you could give it a try? Thanks in advance.

**Comment by largeden** [comment]
@stefanneculai 
The issue has not been resolved yet.
The new demo page looks like the issue is resolved.

![ie11_entering3](https://user-images.githubusercontent.com/5575931/45398859-ce6b2e80-b680-11e8-9160-63bd7fcd3666.gif)

But, If `imageUploadURL` is set, the issue will recur.
![ie11_entering](https://user-images.githubusercontent.com/5575931/45398387-d629d380-b67e-11e8-9c33-87d170738b46.gif)

If you break the paragraph, the issue does not occur.
![ie11_entering2](https://user-images.githubusercontent.com/5575931/45398865-d32fe280-b680-11e8-92f0-55f56c2829a7.gif)

**Comment by ilyaskarim** [comment]
Not able to reproduce on the latest version 4.0.12
