### ISSUE TITLE
Caret jumps around in tables when last character in a row is deleted

### ISSUE THREAD

**Issue by LLatch** [froala/wysiwyg-editor#2785]
##### Expected behavior.
Caret should stay in cell when last character is removed using Backspace.

##### Actual behavior.
Caret moves to a different cell instead. Moreover if cell adjoins another cell on the right, deleting the last character in cell on left instantly moves the cell on the right to the left.

##### Steps to reproduce the problem.
Create a two-column table and use Backspace to delete all characters in one cell. 
First try deleting the last character in a cell in the first column and watch the second column cell take its place. 
Then delete all text in a cell on the right and watch the behaviour of the caret.

##### OS.
Windows 10 Home, version 1709

##### Browser.
Google Chrome, Version 63.0.3239.132 (Official Build) (64-bit)

Thanks!

**Comment by mbensch** [comment]
Also observed this behavior on Chrome/Mac OS. We need this fixed as soon as possible. It's a big issue. We're about to announce and release our new editor which is based on Froala.

Here's a video: https://youtu.be/gO-Df6CpYy4

**Comment by stefanneculai** [comment]
@mbensch no update yet. The fix will be included in the next minor release, however, I don't have an ETA to share for it at this moment.

**Comment by nodefiend** [comment]
Greetings! 

Our team , (and our customers) are experiencing this same issue as well. it is causing unexpected behavior :  *happens when deleting in cells *

<img width="585" alt="screen shot 2018-05-29 at 10 35 42 am" src="https://user-images.githubusercontent.com/10778319/40675735-671d36e8-632d-11e8-96b7-d6445aef7c7a.png">

Heres a gify of it happening on your main site.
 (https://www.froala.com/wysiwyg-editor/examples/table-cell-styles)


![froalabug](https://user-images.githubusercontent.com/10778319/40675961-13dea51a-632e-11e8-8f75-0be15d31e26e.gif)

**Comment by stefanneculai** [comment]
Should be fixed on the current master branch.
