### ISSUE TITLE
Make the new paragraph "escape" the formatting of the previous paragraph

### ISSUE THREAD

**Issue by JWaldenback** [froala/wysiwyg-editor#2807]
##### Expected behavior.
When pressing Enter a new paragraph is created. I want the paragraph to be clean (with no formatting kept from the previous paragraph).

##### Actual behavior.
If the previous paragraph is bolded the newly created paragraph will also be bolded. It's the same with underline, italic, font-color and so on.

Does an option exist to make the new paragraph "escape" the formatting of the previous paragraph?

Thank you!

**Comment by stefanneculai** [comment]
We don't have such an option. I marked this as a feature-request and in case there would be more requests, we might add it in the editor.

**Comment by dgroh** [comment]
Why are you guys closing issues if they are approved to be feature requests? Sorry, this is a **bug** and should remain open. It does not make any sense to have a new paragraph inheriting formatting from the previous one. This does not happen for header tags for example. It's over 2 months since this was closed. Please give us un update regarding this as Froala does not provide any milestone!

**Comment by stefanneculai** [comment]
We use this repo only for bug tracking and we do not keep `feature-requests` opened here. The editor is designed that when there is a paragraph being used and enter is hit at the end of the paragraph, it would keep the format that is used in the new paragraph because that is the way most of the web/desktop apps work.
