### ISSUE TITLE
Event handlers are not triggered when CORS return an error

### ISSUE THREAD

**Issue by robinwassen** [froala/wysiwyg-editor#2855]
##### Expected behavior.
The froalaEditor.image.error event should be called if the CORS proxy return an error HTTP status code when pasting images.

##### Actual behavior.
The image is inserted to the DOM with the original without calling any events regarding image uploads, inserts and errors.

##### Steps to reproduce the problem.
**JSFiddle:** https://jsfiddle.net/wc5c3jhk/464/

- Copy the HTML above the image that contains a broken image (eg. returns 403, 404, 500 status code)
- Paste the HTML into the Froala editor
- See that the error handler is not called
- See that the broken image is inserted as is

I included a working image to make sure that the image upload handlers worked as intended.

##### OS.
macOS 11.13

##### Browser.
Chrome 68

##### Related issues
- #2438

**Comment by stefanneculai** [comment]
The image event handlers are being triggered for images inserted via the editor UI and the image events are designed to be triggered for images inserted via the normal flow. I marked this as a feature request, so that we can discuss about it and see if it would be useful to add such an event for pasted images.
