### ISSUE TITLE
Cursor is in wrong table cell when content in cell is only blocks

### ISSUE THREAD

**Issue by petester42** [froala/wysiwyg-editor#2932]
##### Expected behavior.
Insert block element in table cell. Clicking in table cell with block should select cell.

##### Actual behavior.
Insert block element in table cell. Clicking in table cell with block selects next cell.

##### Steps to reproduce the problem.
- Insert a table (2 x 2)
- Insert video in first table cell
- Click in td (not the video)
- Selected cell is the next one

https://embed.plnkr.co/328DrlPGJ8VORNsAEWFR/ 
![jun-29-2018 12-02-40](https://user-images.githubusercontent.com/296718/42102477-f79635e8-7b93-11e8-958c-74561374da30.gif)

##### OS.
macOS High Sierra

##### Browser.
Chrome  67.0.3396.99

**Comment by dianaprajescu** [comment]
The video requires a wrapper that prevents further clicking and writing inside the same table cell. We currently don't have a way to keep the current video functionality and also allow placing the video in a table cell and still permit writing in the same table cell.

**Comment by petester42** [comment]
I was using the video as an example. This is the case with all block elements. We have custom block elements and have problems with selection in a table. Your comment seems to indicate that there is a fix for this but it couldn't be applied to the video element. Could you provide us what this fix would be so we can try it out with our own block elements that aren't the video element?

**Comment by dianaprajescu** [comment]
Thanks for pointing this out. We have investigate it a bit further and it seems that this is a CSS problem caused by the combination of the following 2 properties:
```
vertical-align: bottom;
position: relative;
```
Here is a [jsFiddle](http://jsfiddle.net/p40qox8a/9/) with a basic `contenteditable="true"` example where the problem can be replicated.

`position: relative;` is required in order to have the resize handlers and `vertical-align: bottom;` is used for design purposes, otherwise the image will not appear vertically centered - it will appear to have more bottom margin.
