### ISSUE TITLE
Initialization should not change / format code

### ISSUE THREAD

**Issue by steffanhalv** [froala/wysiwyg-editor#2936]
##### Expected behavior.
No changes should be done to source before interactively using the editor.

##### Actual behavior.
The source is formatted / cleaned on initialization

##### Details.
We have reactive source with watchers for code edited by Froala editor.
If changes are made, a notice is added to users which sees 'Unsaved changes' so they dont forget to save their text.

Froala editor is modifying the source on initialization which applies the 'changed content' notice.

It would be much better if source is not touched before interactively using the editor.

##### Steps to reproduce the problem.
Initialize a textarea with html code in value

##### OS.
macOS High Sierra, Win 10 etc..

##### Browser.
Chrome, firefox, ie, safari, opera etc.. Latest

**Comment by stefanneculai** [comment]
When the editor is being initialized, a cleanup and some changes are made over to the HTML in order to provide a smooth editing experience. What we would recommend is to get the HTML value in the `initialized` event and compare the HTML you have with that one. Another approach could be to listen to the `contentChanged` event and see when it is triggered.
