### ISSUE TITLE
Korean(Hangul) is not properly entered in Image Caption.

### ISSUE THREAD

**Issue by mirazero** [froala/wysiwyg-editor#2958]
##### Expected behavior.
If you input Korean(Hangul) with Image Caption of inserted image, it should be input properly.

##### Actual behavior.
If you input Korean(Hangul) with image caption, you will not be able to input correctly and you will see broken image caption in IE. Work fine in chrome.

##### Steps to reproduce the problem.
1. Run Internet explorer as web browser.
2. Then, go to https://www.froala.com/wysiwyg-editor.
3. Upload an image from the [insert image] menu in the toolbar.
4. Select the image and choose the [Image Caption] menu from the pop-up menu.
5. Inputting Korean(Hangul) with Image Caption does not work properly. 

##### OS.
Windows 7

##### Browser.
IE 11

**Comment by stefanneculai** [comment]
@mirazero could you please provide a video showing the problem and let us know what keys are you pressing on a QWERTY keyboard?

**Comment by mirazero** [comment]
[details.zip](https://github.com/froala/wysiwyg-editor/files/2197693/details.zip)

![ok-in-chrome](https://user-images.githubusercontent.com/10137404/42760457-801193e0-8945-11e8-8c53-33227dc446c9.png)
![error-in-ie](https://user-images.githubusercontent.com/10137404/42760458-80417574-8945-11e8-81da-bb0eb8b77bf4.png)

I uploaded the video and image files for this issue.
In Chrome, image captions are normally entered, but in IE, there is an error.
Please check this.
Thanks

**Comment by skhydcos** [comment]
I am waiting for a reply.

**Comment by stefanneculai** [comment]
@skhydcos could you please let us know what keys are you pressing there on a QWERTY keyboard?

@largeden do you think you could help us a little bit with steps to reproduce this? Thanks a million in advance! 🙏

**Comment by largeden** [comment]
This issue is a bug in ie11.
(It took a lot of time to reproduce this issue.)

You can reproduce it by following the procedure below.
(It can also be reproduced in other WYSIWYG editors.)

- OS: Windows 10 pro
- browser: ie11
- keyboard: Korean QWERTY keyboard
- input: r + k + s + k

![ie11_bug](https://user-images.githubusercontent.com/5575931/43039561-f947e574-8d6a-11e8-9bb7-2153d25f399b.gif)

https://codepen.io/romanesque/pen/zLNmZB

### solution
The issue occurs if you IME mode in input the text under the following conditions:
````html
<span contenteditable="false">
  <span contenteditable="true">caption</span>
</span>
````

In the image plugins the ie11(`editor.browser.msie`) should remove the `contenteditable` global property.

`_syncImages()`
`toggleCaption()`

**Comment by stefanneculai** [comment]
Thanks for all the details, @largeden. We will be able to address this now.

**Comment by stefanneculai** [comment]
Should be fixed on the current master.
