### ISSUE TITLE
How do I disable draggable=true on videos?

### ISSUE THREAD

**Issue by Geesu** [froala/wysiwyg-editor#2979]
##### Expected behavior.
I'm unable to drag the slider to advance in the video because it attempts to drag the entire video vs. just the slider to move ahead in the video.

Setting `videoMove` to false doesn't help as this doesn't impact the `draggable="true"` HTML attribute. It only removes the `fr-draggable` class.

##### Actual behavior.
The entire video moves.

##### Steps to reproduce the problem.
Upload a video then try to move the slider to advance in the video.

##### OS.
macOS High Sierra.
 
##### Browser.
Chrome 67.0.3396.99

**Comment by stefanneculai** [comment]
Because of the way the browsers are handling the sliders, we cannot keep both video move and dragging the slider. Therefore, I would recommend disabling the [videoMove option](https://www.froala.com/wysiwyg-editor/docs/options#videoMove) if you'd like to be able to move the slider by draf&drop. At this moment, it is possible to move it by click only with videoMove enabled.
