### ISSUE TITLE
`events.trigger` returns undefined if event is not handled outside editor

### ISSUE THREAD

**Issue by petester42** [froala/wysiwyg-editor#2982]
##### Expected behavior.
When creating custom events the `triggerHandler` overrides the value that would have been returned from the internal callback.
 
##### Actual behavior.
The internal callback value should be returned even if there is no outside `triggerHandler`.

##### Steps to reproduce the problem.
Prerequisite: 
- an event and a callback listening to that event

Steps: 
- trigger event
- make callback return something other than false
- check return value

Sample code:
```javascript
if (this.editor.events.trigger("cool_action") === true) {
  console.log("YAY!");
} else {
  console.log("BOO!");
}

_init() {
  editor.events.on("cool_action", () => {
    return true;
  })
}
```
In the example above it will always be `BOO!` because the `triggerHandler` doesn't exist which overrides the return val.

##### OS.
macOS High Sierra

##### Browser.
Chrome  67.0.3396.99

**Comment by stefanneculai** [comment]
The editor is wrapping the events over the jQuery `triggerHandler` method. When `triggerHandler` doesn't exist, then an error would be thrown. The `events.trigger` method is not designed to return a specific value because in case there are multiple events, there is no order between them. That is why, there is also the `events.chainTrigger` method (https://www.froala.com/wysiwyg-editor/docs/methods#events.chainTrigger) which returns the value as you're looking for.

**Comment by petester42** [comment]
Ill try it again, I’ll have to make sure the return value of chainTrigger is not the original parameter I passed since it would be of the same type. Ideally I would want a hybrid of trigger and chainTrigger where the original parameter would not be returned.
