### ISSUE TITLE
htmlUntouched is removing spaces when removing a whole word

### ISSUE THREAD

**Issue by kristian-puccio** [froala/wysiwyg-editor#3013]
##### Expected behavior.
If you have a series of words and either double click or shift-alt-back to select the whole word and press backspace only the selected characters are removed.

Or if you backspace through a word and remove the last character it also deletes the space behind it.

##### Actual behavior.
An extra space is removed.

##### Steps to reproduce the problem.
https://jsfiddle.net/stormdrain/8vap6zq5/

Enter something like `this is a sentence` and double click on sentence and press backspace.
The space is removed between a and sentence so you have to now press space again.

##### OS.
OSX 10.13.6

##### Browser.
Chrome 69.0.3497.32

**Comment by stefanneculai** [comment]
@kristian-puccio do you think you could provide a recording?

**Comment by kristian-puccio** [comment]
This is a recording using the jsfiddle link above. The only option is that htmlUntouched is true.

https://drive.google.com/file/d/1wHOIueozPDA5oakfPEH1Yj-A0pbF_TI5/view?usp=sharing

**Comment by stefanneculai** [comment]
Thanks for the recording. The `htmlUntouched` option is designed to allow the browser to do all the editing without changing the way the spaces or other elements are used. By default, the browser does not insert non-breaking spaces on delete and that is why instead of the fact that there are 2 spaces, it renders a single one. This is actually how the `htmlUntouched` option should work and we don't consider it a bug.
