### ISSUE TITLE
froalaEditor.contentChanged event fired even though nothing changed

### ISSUE THREAD

**Issue by InciteGmbH** [froala/wysiwyg-editor#3022]
##### Expected behavior.
When click into the editor without changing anything, the contentChanged event should not be fired when leaving the focus of the editor.

##### Actual behavior.
The contentChanged event is fired even though nothing has changed

##### Steps to reproduce the problem.
1. Click into the editor
2. Do not change anything
3. Click outside of the editor (f.e. the span above in example)
4. The contentChanged event is fired even though no change is done

See video here:
[ContentChangedEvenIfNothingChanged.zip](https://github.com/froala/wysiwyg-editor/files/2293153/ContentChangedEvenIfNothingChanged.zip)

See fiddle here:
https://jsfiddle.net/InciteGmbH/ahe21kx9/

##### OS.
WindowsServer 2012

##### Browser.
Chrome Version 68.0.3440.106 (Offizieller Build) (64-Bit)

**Comment by InciteGmbH** [comment]
I do work with html.set. Is there a possibility or a property to set/reset after html.set for having the correct behaviour?

**Comment by stefanneculai** [comment]
We have an internal method which should have worked, `undo.reset`. However, it looks like there is a problem with it. I am reopening this so that we can look into it again.

**Comment by InciteGmbH** [comment]
Do you know the time of release approx? Is there something I can change in source code manually or is there a workaround until the release is available?

**Comment by InciteGmbH** [comment]
Do you know about the release or can you suggest a workaround?

**Comment by javeriaanwer** [comment]
please suggest some work around  as soon as possible, it is disturbing our core functionalities.

**Comment by wolf-daniel** [comment]
Hello, I see this as closed, and I've also taken a look at the reference in #3162.
I tried the solution with `undo.reset()` but it didn't work.

Here's my code:
```javascript
this.editor = new FroalaEditor(`.some-selector`, {
  events: {
    contentChanged: () => {
      const currentHtml = this.editor.html.get();
      // Do something when content changes...
    }
  }
}, () => {
  // This is called when the editor is initialized.
  // initialInstructions is a property this component receives.
  this.editor.html.set(initialInstructions);
  this.editor.undo.reset();
});
```

The problem, as stated in this issue, is that the `contentChanged` event is fired after `html.set()` and something in the inner state of the editor really checks the content set via `html.set()` into something else, which turns out different, hence the `contentChanged` event is fired.
Calling `undo.reset()` after `html.set()` in the initialization function didn't make a change.
I had to add an if-clause of my own in the `contentChanged` function, to compare `initialInstructions` to the value I get from `html.get()`. I'd rather avoid that if possible..

Thank you

**Comment by m-camilleri** [comment]
I see this annoying problem has never been resolved. undo.reset() does not help at all, and @wolf-daniel's workaround remains the only solution, although it's slow and cumbersome and something of a kludge.  Shame.

**Comment by piayo** [comment]
I had same issue. didn't work.
I fired the input event once,  and then used contentChanged.

```js
editor.opts.events.contentChanged = $.noop;

editor.html.set( "<p>Froala Editor</p>" )
editor.undo.reset();

editor.el.dispatchEvent( new CustomEvent( "input" ) ); // trigger

editor.opts.events.contentChanged = someWatchFunction;
```

Thank you.
