### ISSUE TITLE
linkAlwaysBlank should not hide the checkbox

### ISSUE THREAD

**Issue by Mboulianne** [froala/wysiwyg-editor#3066]
##### Expected behavior.
It would be nice to have a way to specify a default value for the checkbox (checked / unchecked) without hiding it.  Moreover, the doc reads as follow

> Specifies the default state of the "Open in new tab" checkbox from the link popup.

It doesn't say that the checkox will also be hidden.

##### Actual behavior.
When I pass linkAlwaysBlank: true to the editor links are created as blank link, however, the checkbox disapears from the modal.  Therefore, the user can't choose if he want to create a blank link or not.

##### Steps to reproduce the problem.
Just read the actual behavior.

##### OS.
All

##### Browser.
All

**Comment by stefanneculai** [comment]
We'll update the docs to reflect that. This option was designed more for those apps where all links should be opened in a new tab. 

For changing the checkbox to be checked by default, the best way would be to use the popups.show event (https://www.froala.com/wysiwyg-editor/docs/events#popups.show.[id]) and update the state there. While, we could easily add such an option, we don't want to add it unless there is more request because we'd grow the code base without a good reason.
