### ISSUE TITLE
adjust only the width of the last column

### ISSUE THREAD

**Issue by yoyomule** [froala/wysiwyg-editor#3139]
Hello, we are testing the table function of frola, we found that when adjusting the width of the last column of the table, it will become the width of each column of the entire table is changing. If I want to adjust only the width of the last column, what should I do? In addition, I found that the form is not WYSIWYG in the output of the print, there will be a lot of changes in the width and style, will it be improved in the future?
Thanks.

**Comment by dianaprajescu** [comment]
Hi there!

Adjusting the width of a table column will automatically adjust the width of the column next to it. This means that adjusting the width of the last column will also adjust the with of the column next to it. For this you would have to use the border that is between the columns that you want to adjust.

Using the table's external borders will result in adjusting the width of the entire table. Since the width of all columns in a table are by default expressed in percent, by adjusting the table with, all columns will adapt to the new width.

Please see the following recording for a demonstration: https://www.dropbox.com/s/1uf9dnm94hv3fqs/Screen%20Recording%202018-11-09%20at%2016.29.18.mov?dl=0

As for your second question, I am not sure I understand what you mean. Could you please make a recording for it? Thanks!

**Comment by stefanneculai** [comment]
I am closing this due to lack of response. I would be happy to reopen it if we get more details.
