### ISSUE TITLE
tui crashing

### ISSUE THREAD

**Issue by fmay** [froala/wysiwyg-editor#3160]
Loving my first couple of days with Froala. Got almost everything working, but ...

##### Expected behavior.
Show TUI image editor

##### Actual behavior.
Error

`tui-image-editor.min.js:7 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at keyMirror (tui-image-editor.min.js:7)
    at Object.<anonymous> (tui-image-editor.min.js:7)
    at t (tui-image-editor.min.js:7)
    at Object.<anonymous> (tui-image-editor.min.js:11)
    at t (tui-image-editor.min.js:7)
    at Object.<anonymous> (tui-image-editor.min.js:7)
    at t (tui-image-editor.min.js:7)
    at Object.<anonymous> (tui-image-editor.min.js:11)
    at t (tui-image-editor.min.js:7)
    at Object.<anonymous> (tui-image-editor.min.js:10)`

##### Steps to reproduce the problem.
Can't do a fiddle for various reasons. My application runs under Nuxt/VueJS. Everything works fine but this happens on initialization if I include tui as described [here](https://www.froala.com/wysiwyg-editor/examples/tui-advanced-image-editor)

##### OS.
Max OSX

##### Browser.
Chrome 69.0.3497.100

**Comment by stefanneculai** [comment]
In Vue, it might be better to load it like this: https://github.com/nhnent/tui.image-editor#via-package-manager.

**Comment by stefanneculai** [comment]
It is not related to inline toolbar. It would be best to try opening an issue for this [directly to TUI](https://github.com/nhnent/tui.image-editor/issues) as the problem appears to be from that.

**Comment by GraemeFulton** [comment]
No idea why fabric would never work, but I made a workaround:

I created a new `image_tui.min.js` for Froala, and pasted the `fabric.js` and `tui-image-editor.js` code above the regular `image_tui.min.js` code, so the top looks like this:

<img width="300" alt="Screenshot 2019-08-01 at 09 47 54" src="https://user-images.githubusercontent.com/4354786/62279314-bee40800-b441-11e9-960d-b0f1198e484a.png">

Next, I replaced every mention of `_fabric2.default` with `fabric`, so that it's using the main fabric variable from the top of the file.

Finally, I declared a global ImageEditor before the tui code begins. Then, I added this line:

` window.tui = _imageEditor2`, just underneath `module.exports = _imageEditor2.default;`. That makes the tui ImageEditor available to the froala plugin code at the bottom. Here is the full code:

https://gist.github.com/GraemeFulton/5dd8c9bd3c6dff43b1690718a4297845

It could be done more elegantly, but I included all these in one file to be absolutely certain everything was being imported. I had this problem in a React app created in Vulcan.js which runs on Meteor.js.

**Comment by PauloAlmieda** [comment]
I have the same problem. I'm trying to integrate the tui image editor into froala. In my case froala is loaded in a component vue. I imported the following libs:
 "tui-image-editor"
"tui-code-snippet"
"tui-color-picker"
"fabric"

but it does not work.
