### ISSUE TITLE
ed.html.set still eats whitespace in some cases

### ISSUE THREAD

**Issue by mikesul** [froala/wysiwyg-editor#3178]
This is roughly a continuation of #2753. The fix from this appears to have resolved the issue with back to back images, but it also happens with other inline content, such as a bold tag followed by an image:

##### Expected behavior.
The whitespace node should be maintained.

##### Actual behavior.
Whitespace node is removed.

##### Steps to reproduce the problem.

1. View the fiddle: https://jsfiddle.net/ost24Lzv/
2. Check the browser console
3. Note that the result HTML is missing the space between the closing of the strong tag and the img.

##### OS.
N/A

##### Browser.
N/A

**Comment by chrisdeeming** [comment]
@stefanneculai I'm not actually seeing this fixed in Froala 2.9.3.

The test case was rather clear, the console output result HTML is missing the space between the closing tag of the strong tag and the img tag, and that still appears to be the case:

![image](https://user-images.githubusercontent.com/2158514/53300033-084c7d80-383a-11e9-9034-c80a83cb188c.png)

**Comment by stefanneculai** [comment]
That is strange - it looks we have written the test case for this incorrectly.
