### ISSUE TITLE
Editor scrolls to top when clicking an editor toolbar button

### ISSUE THREAD

**Issue by brycehill** [froala/wysiwyg-editor#3296]
I originally posted this issue [here](https://github.com/froala/wysiwyg-editor/issues/3107#issuecomment-452493510
), but the problem persists in 2.9.3.

#### Expected behavior.
The editor does not scroll up when clicking a toolbar button (such as "bold")

#### Actual behavior.
The editor _does_ scroll up when losing focus and then clicking a toolbar button such as bold.

#### Steps to reproduce the problem.
**Fiddle:** https://jsfiddle.net/8u1oms74/
1. Add enough text to textarea to ensure the editor is scrollable.
2. Click outside of textarea
3. Click "bold" or another toolbar button.
4. Note how the textarea scrolls to the top

#### OS.
MacOS

#### Browser.
Chrome

#### Recording.
Here is a gif where I scroll to the bottom of `.fr-wrapper`, click outside of the textarea to lose focus, and then click the "bold" option in the toolbar. Note how the scroll bar scrolls to the top of the textarea. 

![2019-01-08 16 39 50](https://user-images.githubusercontent.com/2396642/50865711-1dda1680-1364-11e9-9b46-9950aa8f0efd.gif)

**Comment by stefanneculai** [comment]
@brycehill when you click outside of the editor, the editor is losing the focus - you can see that the cursor is no longer in the editor. Then, when using a button, it is scrolling back up because it focuses at the beginning of the editor which is the behavior we have in place when no focus is active. At this moment, we don't have a feature to store position when the editor is unfocused - it would be great if you could suggest it to our roadmap: https://wysiwyg-editor-roadmap.froala.com/public.
