### ISSUE TITLE
Add to videoAllowedProviders default?

### ISSUE THREAD

**Issue by george-norris-salesforce** [froala/wysiwyg-editor#3354]
Hello,

Is there a clean way to add to the existing default videoAllowedProviders, without copying library code into application code?  i.e. I could copy `VIDEO_PROVIDERS` from `video.js` and add my own to that array. 

But if Froala updates `VIDEO_PROVIDERS`, I would not catch the update. Also would like to keep the library code in the module, and app code seperate.

Something like.. would be great:   
```
import myCustomProvider from '../myCustomProvider';

....
videoAllowedProviders: ['.*', myCustomProvider],
....
```

Is there another way to make addendums to videoAllowedProviders?

**Comment by stefanneculai** [comment]
```js
FE.VIDEO_PROVIDERS.push({
  // here comes code for video provider;
});
```
`videoAllowedProviders : ['.*']` just allows everything.

**Comment by john-fenton** [comment]
Hey @stefanneculai 

Can you please just clarify what you mean by:

> videoAllowedProviders : ['.*'] just allows everything.

By _"everything"_, were you referring to the items you listed here https://github.com/froala/wysiwyg-editor/issues/2037#issuecomment-309380194 ?

The reason I ask is because adding video from those sources works, however anything else I have tried ([Twitch.tv](https://www.twitch.tv/lpl/clip/TrappedVibrantAdminDuDudu), [Vice](https://video.vice.com/en_us/video/i-d-meets-rina-sawayama/59e61c69177dd40a930d1d95)) throws the default ui error message "Something went wrong. Please try again."
