### ISSUE TITLE
how does froala insert code blocks? how to modify the style of a code block

### ISSUE THREAD

**Issue by kaixuanliang** [froala/wysiwyg-editor#3370]
### _If you have a feature suggestion, please add it on the [Feature List](https://wysiwyg-editor-roadmap.froala.com/public) instead._
how does froala insert code blocks?
how to modify the style of a code 

- [ ] block

##### Expected behavior.
(Describe expected behaviour here)

##### Actual behavior.
(Describe actual behaviour here)

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)

##### OS.
(OS name and version here)

##### Browser.
(Browser name an version here)

##### Recording.
(A recording showing how to reproduce the problem)

**Comment by ilyaskarim** [comment]
Hi Kaixuanliang, The feature you requested is already on our feature list, Please see https://wysiwyg-editor-roadmap.froala.com/public/ideas/3536

**Comment by googman** [comment]
2.5 years have passed. There is still no way to insert a block with a code. Although in comparison with some, everything is not so bad: the well-known company Atlassian has some obvious and simple feature requests hanging open since 2007-2011.

**Comment by bellasimi** [comment]
5 years have passed since it was posted on the official feature calendar. There is still no way. so I make this myself using Froalaeditor's methods `DefineIcon,RegisterCommand`

### Below is the example code

1. make the custom codeblock command
```
import Froalaeditor from "froala-editor";

Froalaeditor.DefineIcon("codeBlock", {
  NAME: "codeBlock",
  SVG_KEY: "codeView",
});
Froalaeditor.RegisterCommand("codeBlock", {
  title: "codeBlock",
  focus: true,
  undo: true,
  refreshAfterCallback: true,
  callback: function () {
    this.paragraphFormat.apply("code");
    this.paragraphFormat.apply("pre");
  },
});
```

2.  apply that in toolbar button config
```
toolbarButtons = {
	...,
  moreMisc: {
    buttons: [..., "codeBlock"],
  },
};

const config = {
    ...
    toolbarButtons,
  };

<FroalaEditorComponent
      tag="textarea"
      ref={editorRef}
      config={config}
      model={value}
      onModelChange={handleContentChange}
    />
```

### Result 
![image](https://github.com/froala/wysiwyg-editor/assets/79133602/732bef91-55c0-4c9e-a671-7373256eab86)

### Issue
When copy VS code and paste, line breaks aren't working properly. 
Because Froala ignore Vs code's one-space new line(It replace newline into &nbsp. Only two-space is replaced with <br> tag.)
[related issue](https://github.com/froala/angular-froala-wysiwyg/issues/499)

**Comment by imransilvake** [comment]
Is there any way to use code Block?

**Comment by bellasimi** [comment]
@imransilvake  I didn't make pr with the above code. so please copy & paste the code to use it ( the final version code is [in this issue](https://github.com/froala/wysiwyg-editor/issues/4746))

**Comment by imransilvake** [comment]
@bellasimi sure. Thank you
