### ISSUE TITLE
In source code view <!DOCTYPE html>, <html>, <body> is not getting saved

### ISSUE THREAD

**Issue by eldhosejoys** [froala/wysiwyg-editor#3602]
In the source code view when we type `<!DOCTYPE html>` and `<html>` on the top of the code and try to save it. It doesn't get saved. Even when I switch over to 'source' and 'editor' view the `<!DOCTYPE html>` is disappearing.

All these elements `<!DOCTYPE html>` , `<html>` , `<body>`, `<title>` gets disappear in codeview.

**Comment by ilyaskarim** [comment]
Hi you need to use htmlAllowedTags option to enable those tags, Please see https://www.froala.com/wysiwyg-editor/docs/options#htmlAllowedTags.

**Comment by casualuser** [comment]
Hello,

It looks like `<html>` and `<body>` tags at the moment filtered out even if enabled via htmlAllowedTags and `<title>` tag converted to custom tag.

In most cases, this is done by design because of this tags related to main html doc structure and also Froala should be initialized on an element inside existing page body so it is not possible to inject properly extra `<html>`, `<body>` and `<title>` tags inside existing `<body>`.

You can build custom flow for saving with 'save' plugin https://www.froala.com/wysiwyg-editor/docs/concepts/save/button and wrap the content to save with extra tags in `save.before`
 event https://www.froala.com/wysiwyg-editor/docs/events#save.before

Something like this:
```
events: {
    'save.before': function (html) {
        return '<!DOCTYPE html><title>My Title</title><body>'+html+'</body>'
    }
}
```

**Comment by casualuser** [comment]
@eldhosejoys I was checking docs and occasionally found this option in rarely visited area
https://www.froala.com/wysiwyg-editor/examples/full-page

it looks like this is exactly what you need

**Comment by eldhosejoys** [comment]
> @eldhosejoys I was checking docs and occasionally found this option in rarely visited area
> https://www.froala.com/wysiwyg-editor/examples/full-page
> 
> it looks like this is exactly what you need

Exactly. Thanks for the Reply.

**Comment by RamGupta07** [comment]
@casualuser I want to enable this fullPage config when something is pasted in source mode. Do we have any event which is triggered when 'input' or 'paste' event occur in source mode.
