### ISSUE TITLE
vertical-separator doesn't work on toolbar when toolbarInline : true

### ISSUE THREAD

**Issue by manttih** [froala/wysiwyg-editor#3715]
#3336 ### Expected behavior.
When Adding '-' on toolbarButtons, the tools should be separated with a horizontal line.

EDIT: this doesn't seem to work on toolbarInline:false either. I tried both FORMATS:

var setButtons = {
	moreText : {
		buttons : [
			'paragraphFormat',
		],
		buttonsVisible : 1
	},
		moreRich : {
		buttons : [
		'bold',
		],
		buttonsVisible : 1
	},
	moreMisc : {
		buttons : [
			'italic',
		],
		buttonsVisible : 1
	}
}

AND

var setButtons = ['paragraphFormat','-', 'bold', '-', 'italic'];

Neither of these work on inline/basic mode.

##### Actual behavior.
doesn't add horizontal line.

##### Steps to reproduce the problem.
go to page: http://www.synergiafoxy.com/froala_testing_bu.php and check the source code. Setup here is very simple, with only three buttons added: 

['paragraphFormat','-', 'bold', '-', 'italic'];

however, the horizontal line is not added.

##### Editor version.
3.0.6

##### OS.
Windows 7

##### Browser.
Firefox (or any other browser)

**Comment by casualuser** [comment]
Hello,

It looks like you're trying to achieve something special with toolbar styling and make it completely vertical. In this case it looks like some kind of css hacking is required because horizontal separators designed to works as vertical-first expanded areas in toolbar but still it should get editor window size smaller than toolbar size.
Please check this jsfiddle - https://jsfiddle.net/womjoy/d3jvo85g/
And also here is how it's rendered in Chrome - https://take.ms/ikpxu and also FF - https://take.ms/j5qkB

**Comment by manttih** [comment]
Thank you for the example - I was trying to get the toolbar buttons to display on top of each other, but I didn't quite understand how to do this. So, this works correctly:

var setButtons = [['paragraphFormat','-', 'bold', '-', 'italic','-',cmdname]];

but I was trying to do it like this:

var setButtons = ['paragraphFormat','-', 'bold', '-', 'italic','-',cmdname];

which doesn't work.
