### ISSUE TITLE
What's  the best approach to capture specific user input (like return)

### ISSUE THREAD

**Issue by adamgins** [froala/wysiwyg-editor#438]
Hi, 

I'd like to capture user input like:

1)  "shift+enter"  - enter new line in Froala
2)  "enter" - send as a message.

Usually I'd look for something like a "keyup" event. I was not sure what the best practices would be for doing something similar with Froala?

**Comment by stefanneculai** [comment]
You should override the method `$.Editable.prototype.handleEnter` and put your custom code in it to work the way you want. However, you should be aware that it's very likely to introduce bugs with such behaviour because each browser handles these different. We'll probably add builtin support for specifying how to add new line shortly.

**Also, we use this repo for bug reporting mainly, not for support. Please use it appropriate.**

**Comment by adamgins** [comment]
Thanks. Ok, I am going to go another direction and just use a non-Froala contenteditable for now. 

Also, I'll direct these sorts of questions via the support channel.
