### ISSUE TITLE
'allowedBlankTags' option does not work

### ISSUE THREAD

**Issue by zelei** [froala/wysiwyg-editor#450]
I would like to use an blank DIV tag in my content, so allowedBlankTags was set to allow DIV tag. But it is removed after I check back from source code editor.

After I have checked the source code, it seams to me that this part of the cleanOutput method operates an empty simple_nodes array.

Maybe I missed something, Could you give me an advice how I can save my empty tags?

**Comment by stefanneculai** [comment]
Could you please give us more details about your use case?

**Comment by zelei** [comment]
Our client wants to add empty DIV tag as a placeholder to the content, so they will be able to inject html code using Google Tag Manager

**Comment by stefanneculai** [comment]
Indeed there was a small issue there. However, you should use a `<span>` instead of a `<div>`. Also, you should put a class to the span tag so that you can identify it after that in Google Tag Manager. It's not OK to use divs because when you use divs inside  a `<p>` tag it splits the `<p>` tag in two.
