### ISSUE TITLE
Unescaping on textareas

### ISSUE THREAD

**Issue by dbackeus** [froala/wysiwyg-editor#461]
If the user types html characters as text such as `<strong>hello</strong>` that content is escaped to `&lt;strong&gt;hello&lt;/strong&gt;`.

If put inside a `<div>` tag and initializing froala on that the code remains escaped.

However if put inside a `<textarea>` tag and froala is initialized on that textarea the strong tag will suddenly be unescaped. This appears to be true for `<script>` tags etc as well allowing js execution.

**Comment by stefanneculai** [comment]
I couldn't reproduce it locally. Could you please make a jsFiddle?

**Comment by dbackeus** [comment]
Here you go:
http://fiddle.jshell.net/dbackeus/cLmydz6j/

**Comment by stefanneculai** [comment]
The last commit is how it actually should work. 

When you initialize the textarea, you should initialize it with `&amp;lt;strong&amp;gt;hello&amp;lt;/strong&amp;gt;` instead. So far the editor was not giving the output like this - the last commit updates that and now the output is corrected by changing `&` to `&amp;` you initialize the editor on a textarea.

**Comment by stefanneculai** [comment]
Last commit is not changing `&` to `&amp;` in the output anymore. That's because you would expect to simply output the edited HTML on the view page and see it displayed correctly. If the entities are outputted like `&amp;entity;`, then you'd have to decode them before displaying, because otherwise you'd see the entity code (`&entity;`) and not the character. Moreover, it wouldn't be consistent with initializing the editor on a `DIV` element.

Textareas have a odd behaviour:
- If you have the HTML `&lt;strong&gt;hello&lt;/strong&gt;`, then it's value would be `<strong>hello</strong>`
- If you have the HTML `<strong>hello</strong>`, then it's value would be as well `<strong>hello</strong>`
- If you have the HTML `&amp;lt;strong&amp;gt;hello&amp;lt;/strong&amp;gt;`, then it's value would be `&lt;strong&gt;hello&lt;/strong&gt;`

That's why if you initialize the editor on a textarea, save the content and then you want to edit the content again, you'd have to encode entities when you set the textarea value. To encode the entities you can use any function similar to `htmlentities` from PHP.

**Comment by dbackeus** [comment]
Seems like the easiest approach would be to avoid using a textarea and rely on `getHTML` for submitting data instead.

Thanks for the detailed info!
