### ISSUE TITLE
&nbsp; gets escaped to &amp;nbsp;

### ISSUE THREAD

**Issue by Crunch09** [froala/wysiwyg-editor#464]
Hi,

the issue occurs if you enter the following commands in the editor ( http://jsfiddle.net/cLmydz6j/4/ ):
Press bold, enter a random word like `hello`, press bold again (so bold is not active anymore), press space and (optionally) enter another string, such that the html view shows something like:
```html
<p><strong>hello</strong>&nbsp;world</p>
```
If you submit the form now, the submitted value is:
```html
<p><strong>hello</strong>&amp;nbsp;world</p>
```

**Comment by Crunch09** [comment]
Additionally it would be great to have normal spaces instead of `&nbsp;` or to have on option to set this behavior.

**Comment by stefanneculai** [comment]
It is not an issue. Inside textareas, the `&` from HTML entities should be changed to `&amp;` in order to keep the HTML entities escaped properly. See http://jsfiddle.net/kye495zv/. To display it as HTML you should use [html_entity_decode](http://www.w3schools.com/php/func_string_html_entity_decode.asp) in PHP for example.

Regarding your 2nd comment, `&nbsp;` is used only after other HTML tags. Otherwise, there might appear some rendering issues sometimes and the space not appear properly.

**Comment by Crunch09** [comment]
Oh, i see, thank you! And sorry for the trouble.

**Comment by jmventar** [comment]
I reproduced same issue with editor initialized in a div. Had to replace all &amp;nbsp; to &nbsp; before save.
