### ISSUE TITLE
When click on the editor with link plugin and iframe:true, an error occurs

### ISSUE THREAD

**Issue by ArtyomMoiseev** [froala/wysiwyg-editor#4649]
##### Expected behavior.
Error does not occur

##### Actual behavior.
Error in console:
Uncaught TypeError: Cannot read properties of undefined (reading 'isEnabled')

##### Steps to reproduce the problem.
1. Initialize Froala editor with link plugin and iframe:true :
`new FroalaEditor('#example', {pluginsEnabled:['link'], iframe:true});`
2. Click on editor

##### Editor version.
4.1.0
##### OS.
Ubuntu 22.04
##### Browser.
Chrome 114

##### Recording.

[click.webm](https://github.com/froala/wysiwyg-editor/assets/42650429/b8c98f01-f1b3-4d57-a83a-4019d678eed6)

**Comment by dcsaszar** [comment]
JSFiddle (from my duplicate report #4657): https://jsfiddle.net/403sjgtd/

**Comment by eliel-jr** [comment]
Hi folks, i will investigated this bug.

I have 2 projects that use the editor, The project where the error occurred used 4.0.19, the project without error uses version 4.0.17

I have 2 projects that use the editor, The project where the error occurred used 4.0.19, the project without error uses version 4.0.17

the bug is located in the 'froala-editor' dependency, not 'ember-froala-editor'.

**Comment by ArtyomMoiseev** [comment]
Still reproduced on 4.1.1.

**Comment by lkristofmc** [comment]
same, solved it by importing this plugin: https://froala.com/markdown-plugin/

**Comment by dcsaszar** [comment]
Confirmed fixed in [4.1.2](https://github.com/froala/wysiwyg-editor/releases/tag/v4.1.2)
