### ISSUE TITLE
Delay saving of images by saving them as data-uri included in the text

### ISSUE THREAD

**Issue by gonsfx** [froala/wysiwyg-editor#600]
Is there a way to do?

The only way i found from looking at the docs is to upload the images when they are added.

**Comment by kristoftorfs** [comment]
I solved this by letting the upload script return the data-uri.

**Comment by gonsfx** [comment]
Thats an unfortunate hack because it does additional client-server roundtrips.

**Comment by stefanneculai** [comment]
You can use https://www.froala.com/wysiwyg-editor/docs/events#beforeImageUpload.

**Comment by gonsfx** [comment]
That doesn't answer my question.

Can i use `beforeImageUpload` to cancel the upload?
Can i somehow add the images data-uris to the editors contents?

**Comment by stefanneculai** [comment]
The documentation explains that you can cancel the image upload by returning `false`. Then you can use the images param from the event to get the image and insert it into the editor using the `writeImage` method. However, it is not recommended to use images this way because the browsers doesn't handle very well images in base64 inside contenteditable elements and you might end with a non-responding page.

We use this repo mainly for bug tracking. If you have questions or need help integrating the editor please [contact us](https://www.froala.com/wysiwyg-editor/contact) instead of opening an issue.

**Comment by gonsfx** [comment]
If you know that by 'paste event' you mean 'upload request', yes. To me, that wasn't clear.

Thanks for clarification!

On a sidenote, i don't see how helping with integration in private helps your business. If you would offer help here, others could benefit from your answers aswell.

**Comment by stefanneculai** [comment]
Thanks for letting us know about the typo in the docs. It's fixed now.
