### ISSUE TITLE
Caret appears on top of popups and toolbar

### ISSUE THREAD

**Issue by felskov** [froala/wysiwyg-editor#752]
On iOS 8.4 the caret and selections will appear on top of popups. This is not a major issue, but it still seems like a bug. We've tested a few things in regard to this, and what worked best for us was to:

1. Save and then clear selection when the user opens a popup - and then restoring the selection onHide. Obviously this requires each plugin to wait for the selection to be restored before any actions are done, but we did manage to get a working solution ready for the image plugin, and it seemed to solve the issue perfectly.

2. Rendering a fixed size editor, where the content does not flow under the toolbar, solves the issue of the caret being on top of the toolbar. Much the same way for instance TinyMCE works. It would be great to have an option for doing this.

<img width="347" alt="screen shot 2015-09-17 at 11 42 36" src="https://cloud.githubusercontent.com/assets/1436954/9930070/58e8cae2-5d31-11e5-9cd0-5e4bb183b88c.png">

<img width="371" alt="screen shot 2015-09-17 at 11 42 58" src="https://cloud.githubusercontent.com/assets/1436954/9930072/58ebedbc-5d31-11e5-9a00-799d42fd2acd.png">

<img width="345" alt="screen shot 2015-09-17 at 11 43 25" src="https://cloud.githubusercontent.com/assets/1436954/9930071/58ea435e-5d31-11e5-88fd-768f1ab516a8.png">

**Comment by stefanneculai** [comment]
This a known iOS issue that we have reported to Apple and discussed about it in the past. During the development of v2 we did some good research about this and your workaround is working but not all the time because it might break the native focus/blur events. For us it was important to have the editor not messing the browser focus/blur events like other editors do and it was implemented like this.

I am marking this as enhancement and we will review it once again to see it we could find a better approach.

**Comment by rblin081** [comment]
This is an issue for v2.1.1 in IE 11 as well

**Comment by stefanneculai** [comment]
@rblin081 it's a browser issue as well.

**Comment by stefanneculai** [comment]
I am closing this for now because we consider it as being a browser issue and there is nothing we could do to avoid it.
