### ISSUE TITLE
Fixed size popup trouble

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/wysiwyg-editor#824]
As on screen:

http://prntscr.com/8o4u5b

http://prntscr.com/8o4un2 (here is potential problem: for example wysiwyg is 400px width, and on right somebody have another block, then this popup will be hidden. In v1 this popup's where attached to body, and all was ok, how to be now?)

**Comment by stefanneculai** [comment]
The height of the editor should be set using the builtin option: https://www.froala.com/wysiwyg-editor/v2.0/docs/examples/predefined-height. In V2, the popups are not attached to the body in order to improve the scrolling experience.

If you believe there is a problem with that issue, please make a jsFiddle and send us the steps to replicate it.

**Comment by kotmatpockuh** [comment]
bad idea
how to be, if height is dynamic (css media queries)?

**Comment by kotmatpockuh** [comment]
same issue! 
http://prntscr.com/8o5109

i entered 20 time 'enter' key and then added image
as result: bug

**Comment by stefanneculai** [comment]
Last commit fixes it. Actually, in v2 RC3, the popups are appended to the scrollableContainer like they were in v1.

**Comment by kotmatpockuh** [comment]
also:

"how to be, if height is dynamic (css media queries)?
also user can have different browser window height"

**Comment by stefanneculai** [comment]
Could you please explain the problem in more detail? What are you doing, what is the expected behaviour, what actually happens.

**Comment by kotmatpockuh** [comment]
height of my wysiwyg is dynamic, not predefined, and depends on browsers height (also height of container is different for each device type)
i need to set dynamic height of wysiwyg (btw: i need to set custom scrollableContainer to append popups to the body)

**Comment by stefanneculai** [comment]
If you want to get it fixed, then we'd need to know:
1) What are you doing.
2) What is the expected behaviour.
3) What is the actual behaviour.

A jsFiddle would help in fixing it quicker if there is any problem.

**Comment by kotmatpockuh** [comment]
1) I need to set wysiwyg content height to it's parent height, which is not fixed, but fluid
2) Content height matched to fluid parent
3) Own wysiwyg height, option `height` is only for fixed size height.

http://plnkr.co/edit/FO9VDEEuAHHHZlV2K2zD?p=preview


![Image of Froala](http://i.imgur.com/TP5nxKr.png)

**Comment by kotmatpockuh** [comment]
@stefanneculai 
so, any news?

**Comment by stefanneculai** [comment]
The height of the editor cannot be set to match the parent size with the built-in feature of the editor.

However, the height of the editor can be changed using the [height](https://www.froala.com/wysiwyg-editor/docs/options#height) option and then calling the [size.refresh](https://www.froala.com/wysiwyg-editor/docs/methods#size.refresh) method. To set the height option after initialization you should use `$(selector).data('froala.editor').opts.height = new_height;`. 

Setting the height using CSS is not the correct way because there are some other internal setups that have to be made.
