### ISSUE TITLE
V2: How to set option after initialization

### ISSUE THREAD

**Issue by bsboris** [froala/wysiwyg-editor#879]
There used to be the `option` method in the first version, but it was removed. How can I change or add an option after the editor has been initialized?

**Comment by stefanneculai** [comment]
https://github.com/froala/wysiwyg-editor/issues/778#issuecomment-142609365

**Comment by cubet-rahul** [comment]
Hello,
I want to add the "fileUploadURL" dynamically because it is a result of API response. I think it is not possible to update the option and need to destroy the current instance and should create a new instance with new options. I work in angular and tries to update the "fileUploadURL" in a constructor function. Here is my code:

@Component({
  selector: 'app-add-service',
  templateUrl: './add-service.component.html',
  styleUrls: ['./add-service.component.scss']
})
export class AddServiceComponent implements OnInit {

  public options: Object = {
    placeholderText: 'Add Your Note Here!',
    charCounterCount: false,
    fileUploadMethod: 'POST',
    fileMaxSize: 20 * 1024 * 1024,
    fileAllowedTypes: ['*'],
    events : {
      'froalaEditor.focus' : function(e: any, editor: any) {
        console.log(editor.selection.get());
      },
      'froalaEditor.file.beforeUpload' : function(e: any, editor: any, files: any) {
         return true;
      },
      'froalaEditor.file.uploaded' : function(e: any, editor: any, response: any) {
        console.log('RS', response);
        return true;
      },
      'froalaEditor.file.error' : function(e: any, editor: any, error: any, response: any) {
        console.log('ERROR', error);
        return true;
      }
    }
  };

  constructor() {
    this.setFileUploadUrl();
  }

  ngOnInit() {
  }

  setFileUploadUrl() {
    const fileTypes = ['application/pdf'];
    this.servicesService.getUploadUrl(fileTypes).subscribe((response: any) => {
      this.options = Object.assign(this.options, {
        fileUploadURL: response[0].uploadURL
      });
    });
  }

<div [froalaEditor]="options" [(froalaModel)]="content"></div>

This code does not trigger the 'froalaEditor.file.uploaded' event. So how can  I destroy the current instance and create a new instance with new additional options?

**Comment by Argorate** [comment]
I try to change some options after initit like : 

```
    self.data('froala.editor').opts.placeholderText = placeholder
    self.froalaEditor('placeholder.refresh')
    self.data('froala.editor').opts.charCounterMax = maxlength
   self.froalaEditor('charCounterMax.refresh') # <====== function doesnt exist...
```

How can I refrech the charCounterMax ?

**Comment by stefanneculai** [comment]
@andelf you can refresh the charCounter by calling the contentChanged event:
```js
froalaEditor('events.trigger', 'contentChanged');
```
