### ISSUE TITLE
Sticky toolbar position is misplaced in Semantic UI

### ISSUE THREAD

**Issue by ericleethrinacia** [froala/wysiwyg-editor#960]
I have downloaded the latest version from master and really appreciate the responses you give
I've noticed that sticky toolbar's position is misplaced in accordion in Semantic UI 1
When I keep scrolling, the toolbar's position becomes just above the browser window
It was working in the official release of 2.0.1

**Comment by stefanneculai** [comment]
We haven't changed anything related to the sticky toolbar. Please make a jsFiddle for it.

**Comment by stefanneculai** [comment]
The problem is coming from a CSS translate that Semantic UI does. Disabling the translate will make the editor work correctly. Unfortunately, this is a Webkit problem and there is no workaround for it.

I am attaching a screenshot with the CSS rules in case anyone has the same problem.

<img width="328" alt="screen shot 2015-12-04 at 01 27 00" src="https://cloud.githubusercontent.com/assets/637004/11577944/fe769c66-9a29-11e5-94f0-0a05b6cc7f71.png">
