### ISSUE TITLE
IE / override website font and color settings --> menu button are unappeared

### ISSUE THREAD

**Issue by open2** [froala/wysiwyg-editor#990]
http://windows.microsoft.com/en-us/windows/change-webpage-colors-fonts#1TC=windows-7

IE 11/
Internet Options -> General (tab) -> (Click) Accessibility -> (select) Ignore colors specified on webpages, Ignore font styles specified on webpages

menu buttons of froala are  unappeared.

![froala_unappeared](https://cloud.githubusercontent.com/assets/2640011/11868836/0fbad954-a4fe-11e5-8a15-d331ddac8f20.GIF)

**Comment by stefanneculai** [comment]
The editor is using FontAwesome by default for icons and that's why buttons disappear. However, if you want you can use images instead: https://www.froala.com/wysiwyg-editor/docs/concepts/custom-icon.

**Comment by open2** [comment]
people can use this IE option for easy reading.
please add text menu appearence in this case.

this reuqest is for disabled people.

**Comment by open2** [comment]
disabled people makes font option disable.
they can not see small font-awesome icons.

thanks.

**Comment by stefanneculai** [comment]
I understand that, however it is not possible what you're asking for. By default, the editor uses Font Awesome for displaying icons, which basically is a font. Disabling fonts, would also disable the editor buttons because they are using the font option.

If one of your website requirements is to have it work with fonts disabled, then you can customize the editor buttons and use images instead because it is the only way you could get it work correctly for your use case. Details about that are available in [our docs](https://www.froala.com/wysiwyg-editor/docs/concepts/custom-icon), but here is what you mainly should do:
```js
<!-- Include the editor JS and CSS -->
<script>
  // Change the default icon template.
  $.FroalaEditor.ICON_DEFAULT_TEMPLATE = 'material_design';
  
  // Define the icons for the editor buttons. 
  // For each icon you use in the toolbar, you should specify what image to use.
  $.FroalaEditor.DefineIcon('bold', {
    SRC: '/path/to/bold.png',
    ALT: 'Bold'
  });

  $.FroalaEditor.DefineIcon('bold', {
    SRC: '/path/to/italic.png',
    ALT: 'Italic'
  });
</script>
```
