### ISSUE TITLE
Supporting "required" attribute

### ISSUE THREAD

**Issue by nicolasbocquet** [froala/wysiwyg-editor#994]
Hi,

I tried to add the required="required" attribute on a textarea that is replaced by froala, but I think it is not supported yet as the browser tooltip is placing himself at the top left corner of the viewport.

May I suggest you to add this feature to froala ? ;)

**Comment by stefanneculai** [comment]
The editor doesn't come with any such feature builtin. If you want to check that the editor is not empty, then you should use the `html.get` method and then display if the error message.

**Comment by jgerigmeyer** [comment]
This is frustrating, because it causes errors in Chrome when a form is submitted without anything entered in a `required` textarea (i.e., native browser form validation).

See: https://jsfiddle.net/jgerigmeyer/dffhnu7L/1/

If you submit the form without entering anything in the Froala editor, it throws an error (`An invalid form control with name='content' is not focusable.`) instead of showing the browser validation message.

**Comment by stephen-puiszis** [comment]
+1 this seems like a good feature to implement and I'm facing similar frustrations as well.

**Comment by allomov** [comment]
Do you have any news on this issue? It looks, like our customer has the same issue.

**Comment by allomov** [comment]
@stephen-puiszis actually it is easy to fix this issue by adding `novalidate` attribute to the form with editor, like this:
```
$('form#resource_html')..froalaEditor({...})
$('form#resource_html').attr("novalidate", true)
```

**Comment by allomov** [comment]
Looks like the solution that I've provided fails to work in chrome.
